// src/modules/entidades/dto/guardar-entidad.dto.ts
import { IsIn, IsOptional, IsString, MaxLength } from 'class-validator';

/** Everything about a managing entity except its code, all optional. */
class CamposEntidadDto {
  @IsOptional()
  @IsString()
  @MaxLength(120)
  nombre?: string;

  @IsOptional()
  @IsString()
  @MaxLength(20)
  nit?: string;

  @IsOptional()
  @IsString()
  @MaxLength(2)
  digitoVerificacion?: string;

  @IsOptional()
  @IsString()
  @MaxLength(120)
  email?: string;

  @IsOptional()
  @IsString()
  @MaxLength(30)
  telefono?: string;
}

/**
 * `codigo` is deliberately absent: it's auto-generated by
 * `EntidadesService.siguienteCodigo()`, never supplied by the caller.
 */
export class CrearEntidadDto extends CamposEntidadDto {}

/**
 * `estado` is here, and it is the only way this record is retired: deactivating
 * a managing company suspends the access its assignments grant, without
 * touching the buildings it administers — a coproperty outlives whoever runs
 * it. There is no delete.
 */
export class ActualizarEntidadDto extends CamposEntidadDto {
  @IsOptional()
  @IsIn(['activo', 'inactivo'])
  estado?: 'activo' | 'inactivo';
}
