// src/modules/catalogos/catalogos.data.ts
//
// Tipos de documento, departamentos y municipios exactamente como los
// publica la DIAN/el DANE — generado a partir de los archivos oficiales que
// el cliente proveyó (tabla_Identificacion.XLS, tabla_Departamentos.XLS,
// tabla_ciudades.XLS), no transcrito a mano.
//
// Datos estáticos por diseño: no viven en Mongo porque no cambian salvo una
// nueva resolución DIAN, y no hay ninguna pantalla para editarlos — son un
// catálogo de solo lectura, igual para toda copropiedad y toda instalación.
// `CiudadDian.departamentoCodigo` son los primeros dos dígitos del propio
// `codigo` del municipio (el estándar DANE los codifica así), pero se
// guarda explícito en cada fila para no obligar a quien lo consuma a saber
// ese detalle de codificación.

export interface TipoIdentificacionDian {
  codigo: string;
  nombre: string;
}

export interface DepartamentoDian {
  codigo: string;
  nombre: string;
}

export interface CiudadDian {
  codigo: string;
  nombre: string;
  departamentoCodigo: string;
}

export const TIPOS_IDENTIFICACION_DIAN: TipoIdentificacionDian[] = [
  { codigo: '11', nombre: 'Registro Civil' },
  { codigo: '12', nombre: 'Tarjeta de Identidad' },
  { codigo: '13', nombre: 'Cedula de Ciudadania' },
  { codigo: '21', nombre: 'Tarjeta de Extranjeria' },
  { codigo: '22', nombre: 'Cedula de Extranjeria' },
  { codigo: '31', nombre: 'Nit' },
  { codigo: '41', nombre: 'Pasaporte' },
  { codigo: '42', nombre: 'Identificacion Extranjero' },
  { codigo: '47', nombre: 'PEP (permiso permanencia)' },
  { codigo: '48', nombre: 'PPT (permiso temporal)' },
  { codigo: '50', nombre: 'NIT de Otro Pais' },
  { codigo: '91', nombre: 'NUIP' },
];

export const DEPARTAMENTOS_DIAN: DepartamentoDian[] = [
  { codigo: '91', nombre: 'Amazonas' },
  { codigo: '05', nombre: 'Antioquia' },
  { codigo: '81', nombre: 'Arauca' },
  { codigo: '08', nombre: 'Atlantico' },
  { codigo: '11', nombre: 'Bogota' },
  { codigo: '13', nombre: 'Bolivar' },
  { codigo: '15', nombre: 'Boyaca' },
  { codigo: '17', nombre: 'Caldas' },
  { codigo: '18', nombre: 'Caqueta' },
  { codigo: '85', nombre: 'Casanare' },
  { codigo: '19', nombre: 'Cauca' },
  { codigo: '20', nombre: 'Cesar' },
  { codigo: '27', nombre: 'Choco' },
  { codigo: '23', nombre: 'Cordoba' },
  { codigo: '25', nombre: 'Cundinamarca' },
  { codigo: '94', nombre: 'Guainia' },
  { codigo: '95', nombre: 'Guaviare' },
  { codigo: '41', nombre: 'Huila' },
  { codigo: '44', nombre: 'La Guajira' },
  { codigo: '47', nombre: 'Magdalena' },
  { codigo: '50', nombre: 'Meta' },
  { codigo: '52', nombre: 'Narino' },
  { codigo: '54', nombre: 'Norte de Santander' },
  { codigo: '86', nombre: 'Putumayo' },
  { codigo: '63', nombre: 'Quindio' },
  { codigo: '66', nombre: 'Risaralda' },
  { codigo: '88', nombre: 'San Andres y Providencia' },
  { codigo: '68', nombre: 'Santander' },
  { codigo: '70', nombre: 'Sucre' },
  { codigo: '73', nombre: 'Tolima' },
  { codigo: '76', nombre: 'Valle del Cauca' },
  { codigo: '97', nombre: 'Vaupes' },
  { codigo: '99', nombre: 'Vichada' },
];

export const CIUDADES_DIAN: CiudadDian[] = [
  { codigo: '05002', nombre: 'Abejorral', departamentoCodigo: '05' },
  { codigo: '05001', nombre: 'Medellin', departamentoCodigo: '05' },
  { codigo: '05004', nombre: 'Abriaqui', departamentoCodigo: '05' },
  { codigo: '05021', nombre: 'Alejandria', departamentoCodigo: '05' },
  { codigo: '05030', nombre: 'Amaga', departamentoCodigo: '05' },
  { codigo: '05031', nombre: 'Amalfi', departamentoCodigo: '05' },
  { codigo: '05034', nombre: 'Andes', departamentoCodigo: '05' },
  { codigo: '05036', nombre: 'Angelopolis', departamentoCodigo: '05' },
  { codigo: '05038', nombre: 'Angostura', departamentoCodigo: '05' },
  { codigo: '05040', nombre: 'Anori', departamentoCodigo: '05' },
  { codigo: '05042', nombre: 'Santafe de Antioquia', departamentoCodigo: '05' },
  { codigo: '05044', nombre: 'Anza', departamentoCodigo: '05' },
  { codigo: '05045', nombre: 'Apartado', departamentoCodigo: '05' },
  { codigo: '05051', nombre: 'Arboletes', departamentoCodigo: '05' },
  { codigo: '05055', nombre: 'Argelia - Antioquia', departamentoCodigo: '05' },
  { codigo: '05059', nombre: 'Armenia - Antioquia', departamentoCodigo: '05' },
  { codigo: '05079', nombre: 'Barbosa', departamentoCodigo: '05' },
  { codigo: '05086', nombre: 'Belmira', departamentoCodigo: '05' },
  { codigo: '05088', nombre: 'Bello', departamentoCodigo: '05' },
  { codigo: '05091', nombre: 'Betania', departamentoCodigo: '05' },
  { codigo: '05093', nombre: 'Betulia - Antioquia', departamentoCodigo: '05' },
  { codigo: '05101', nombre: 'Ciudad Bolivar', departamentoCodigo: '05' },
  { codigo: '05107', nombre: 'Briceno - Antioquia', departamentoCodigo: '05' },
  { codigo: '05113', nombre: 'Buritica', departamentoCodigo: '05' },
  { codigo: '05120', nombre: 'Caceres', departamentoCodigo: '05' },
  { codigo: '05125', nombre: 'Caicedo', departamentoCodigo: '05' },
  { codigo: '05129', nombre: 'Caldas - Antioquia', departamentoCodigo: '05' },
  { codigo: '05134', nombre: 'Campamento', departamentoCodigo: '05' },
  { codigo: '05138', nombre: 'Canasgordas', departamentoCodigo: '05' },
  { codigo: '05142', nombre: 'Caracoli', departamentoCodigo: '05' },
  { codigo: '05145', nombre: 'Caramanta', departamentoCodigo: '05' },
  { codigo: '05147', nombre: 'Carepa', departamentoCodigo: '05' },
  { codigo: '05148', nombre: 'El Carmen de Viboral', departamentoCodigo: '05' },
  { codigo: '05150', nombre: 'Carolina', departamentoCodigo: '05' },
  { codigo: '05154', nombre: 'Caucasia', departamentoCodigo: '05' },
  { codigo: '05172', nombre: 'Chigorodo', departamentoCodigo: '05' },
  { codigo: '05190', nombre: 'Cisneros', departamentoCodigo: '05' },
  { codigo: '05197', nombre: 'Cocorna', departamentoCodigo: '05' },
  {
    codigo: '05206',
    nombre: 'Concepcion - Antioquia',
    departamentoCodigo: '05',
  },
  {
    codigo: '05209',
    nombre: 'Concordia - Antioquia',
    departamentoCodigo: '05',
  },
  { codigo: '05212', nombre: 'Copacabana', departamentoCodigo: '05' },
  { codigo: '05234', nombre: 'Dabeiba', departamentoCodigo: '05' },
  { codigo: '05237', nombre: 'Don Matias', departamentoCodigo: '05' },
  { codigo: '05240', nombre: 'Ebejico', departamentoCodigo: '05' },
  { codigo: '05250', nombre: 'El Bagre', departamentoCodigo: '05' },
  { codigo: '05264', nombre: 'Entrerrios', departamentoCodigo: '05' },
  { codigo: '05266', nombre: 'Envigado', departamentoCodigo: '05' },
  { codigo: '05282', nombre: 'Fredonia', departamentoCodigo: '05' },
  { codigo: '05284', nombre: 'Frontino', departamentoCodigo: '05' },
  { codigo: '05306', nombre: 'Giraldo', departamentoCodigo: '05' },
  { codigo: '05308', nombre: 'Girardota', departamentoCodigo: '05' },
  { codigo: '05310', nombre: 'Gomez Plata', departamentoCodigo: '05' },
  { codigo: '05313', nombre: 'Granada - Antioquia', departamentoCodigo: '05' },
  {
    codigo: '05315',
    nombre: 'Guadalupe - Antioquia',
    departamentoCodigo: '05',
  },
  { codigo: '05318', nombre: 'Guarne', departamentoCodigo: '05' },
  { codigo: '05321', nombre: 'Guatape', departamentoCodigo: '05' },
  { codigo: '05347', nombre: 'Heliconia', departamentoCodigo: '05' },
  { codigo: '05353', nombre: 'Hispania', departamentoCodigo: '05' },
  { codigo: '05360', nombre: 'Itagui', departamentoCodigo: '05' },
  { codigo: '05361', nombre: 'Ituango', departamentoCodigo: '05' },
  { codigo: '05364', nombre: 'Jardin', departamentoCodigo: '05' },
  { codigo: '05368', nombre: 'Jerico - Antioquia', departamentoCodigo: '05' },
  { codigo: '05376', nombre: 'La Ceja', departamentoCodigo: '05' },
  { codigo: '05380', nombre: 'La Estrella', departamentoCodigo: '05' },
  { codigo: '05390', nombre: 'La Pintada', departamentoCodigo: '05' },
  {
    codigo: '05400',
    nombre: 'La Union -  Antioquia',
    departamentoCodigo: '05',
  },
  { codigo: '05411', nombre: 'Liborina', departamentoCodigo: '05' },
  { codigo: '05425', nombre: 'Maceo', departamentoCodigo: '05' },
  { codigo: '05440', nombre: 'Marinilla', departamentoCodigo: '05' },
  { codigo: '05467', nombre: 'Montebello', departamentoCodigo: '05' },
  { codigo: '05475', nombre: 'Murindo', departamentoCodigo: '05' },
  { codigo: '05480', nombre: 'Mutata', departamentoCodigo: '05' },
  { codigo: '05483', nombre: 'Narino - Narino', departamentoCodigo: '05' },
  { codigo: '05490', nombre: 'Necocli', departamentoCodigo: '05' },
  { codigo: '05495', nombre: 'Nechi', departamentoCodigo: '05' },
  { codigo: '05501', nombre: 'Olaya', departamentoCodigo: '05' },
  { codigo: '05541', nombre: 'Penol', departamentoCodigo: '05' },
  { codigo: '05543', nombre: 'Peque', departamentoCodigo: '05' },
  { codigo: '05576', nombre: 'Pueblorrico', departamentoCodigo: '05' },
  { codigo: '05579', nombre: 'Puerto Berrio', departamentoCodigo: '05' },
  { codigo: '05585', nombre: 'Puerto Nare', departamentoCodigo: '05' },
  { codigo: '05591', nombre: 'Puerto Triunfo', departamentoCodigo: '05' },
  { codigo: '05604', nombre: 'Remedios', departamentoCodigo: '05' },
  { codigo: '05607', nombre: 'Retiro', departamentoCodigo: '05' },
  { codigo: '05615', nombre: 'Rionegro - Antioquia', departamentoCodigo: '05' },
  {
    codigo: '05628',
    nombre: 'Sabanalarga - Antioquia',
    departamentoCodigo: '05',
  },
  { codigo: '05631', nombre: 'Sabaneta', departamentoCodigo: '05' },
  { codigo: '05642', nombre: 'Salgar', departamentoCodigo: '05' },
  {
    codigo: '05647',
    nombre: 'San Andres de Cuerquia',
    departamentoCodigo: '05',
  },
  {
    codigo: '05649',
    nombre: 'San Carlos - Antioquia',
    departamentoCodigo: '05',
  },
  {
    codigo: '05652',
    nombre: 'San Francisco - Antioquia',
    departamentoCodigo: '05',
  },
  { codigo: '05656', nombre: 'San Jeronimo', departamentoCodigo: '05' },
  {
    codigo: '05658',
    nombre: 'San Jose de la Montana',
    departamentoCodigo: '05',
  },
  { codigo: '05659', nombre: 'San Juan de Uraba', departamentoCodigo: '05' },
  { codigo: '05660', nombre: 'San Luis - Antioquia', departamentoCodigo: '05' },
  {
    codigo: '05664',
    nombre: 'San Pedro de los Milagros',
    departamentoCodigo: '05',
  },
  { codigo: '05665', nombre: 'San Pedro de Uraba', departamentoCodigo: '05' },
  { codigo: '05667', nombre: 'San Rafael', departamentoCodigo: '05' },
  { codigo: '05670', nombre: 'San Roque', departamentoCodigo: '05' },
  { codigo: '05674', nombre: 'San Vicente', departamentoCodigo: '05' },
  {
    codigo: '05679',
    nombre: 'Santa Barbara - Antioquia',
    departamentoCodigo: '05',
  },
  { codigo: '05686', nombre: 'Santa Rosa de Osos', departamentoCodigo: '05' },
  { codigo: '05690', nombre: 'Santo Domingo', departamentoCodigo: '05' },
  { codigo: '05697', nombre: 'El Santuario', departamentoCodigo: '05' },
  { codigo: '05736', nombre: 'Segovia', departamentoCodigo: '05' },
  { codigo: '05756', nombre: 'Sonson', departamentoCodigo: '05' },
  { codigo: '05761', nombre: 'Sopetran', departamentoCodigo: '05' },
  { codigo: '05789', nombre: 'Tamesis', departamentoCodigo: '05' },
  { codigo: '05790', nombre: 'Taraza', departamentoCodigo: '05' },
  { codigo: '05792', nombre: 'Tarso', departamentoCodigo: '05' },
  { codigo: '05809', nombre: 'Titiribi', departamentoCodigo: '05' },
  { codigo: '05819', nombre: 'Toledo - Antioquia', departamentoCodigo: '05' },
  { codigo: '05837', nombre: 'Turbo', departamentoCodigo: '05' },
  { codigo: '05842', nombre: 'Uramita', departamentoCodigo: '05' },
  { codigo: '05847', nombre: 'Urrao', departamentoCodigo: '05' },
  { codigo: '05854', nombre: 'Valdivia', departamentoCodigo: '05' },
  {
    codigo: '05856',
    nombre: 'Valparaiso - Antioquia',
    departamentoCodigo: '05',
  },
  { codigo: '05858', nombre: 'Vegachi', departamentoCodigo: '05' },
  { codigo: '05861', nombre: 'Venecia - Antioquia', departamentoCodigo: '05' },
  { codigo: '05873', nombre: 'Vigia del Fuerte', departamentoCodigo: '05' },
  { codigo: '05885', nombre: 'Yali', departamentoCodigo: '05' },
  { codigo: '05887', nombre: 'Yarumal', departamentoCodigo: '05' },
  { codigo: '05890', nombre: 'Yolombo', departamentoCodigo: '05' },
  { codigo: '05893', nombre: 'Yondo', departamentoCodigo: '05' },
  { codigo: '05895', nombre: 'Zaragoza', departamentoCodigo: '05' },
  { codigo: '08001', nombre: 'Barranquilla', departamentoCodigo: '08' },
  { codigo: '08078', nombre: 'Baranoa', departamentoCodigo: '08' },
  { codigo: '08137', nombre: 'Campo de la Cruz', departamentoCodigo: '08' },
  { codigo: '08141', nombre: 'Candelaria', departamentoCodigo: '08' },
  { codigo: '08296', nombre: 'Galapa', departamentoCodigo: '08' },
  { codigo: '08372', nombre: 'Juan de Acosta', departamentoCodigo: '08' },
  { codigo: '08421', nombre: 'Luruaco', departamentoCodigo: '08' },
  { codigo: '08433', nombre: 'Malambo', departamentoCodigo: '08' },
  { codigo: '08436', nombre: 'Manati', departamentoCodigo: '08' },
  { codigo: '08520', nombre: 'Palmar de Varela', departamentoCodigo: '08' },
  { codigo: '08549', nombre: 'Piojo', departamentoCodigo: '08' },
  { codigo: '08558', nombre: 'Polonuevo', departamentoCodigo: '08' },
  { codigo: '08560', nombre: 'Ponedera', departamentoCodigo: '08' },
  { codigo: '08573', nombre: 'Puerto Colombia', departamentoCodigo: '08' },
  { codigo: '08606', nombre: 'Repelon', departamentoCodigo: '08' },
  { codigo: '08634', nombre: 'Sabanagrande', departamentoCodigo: '08' },
  {
    codigo: '08638',
    nombre: 'Sabanalarga - Atlantico',
    departamentoCodigo: '08',
  },
  { codigo: '08675', nombre: 'Santa Lucia', departamentoCodigo: '08' },
  { codigo: '08685', nombre: 'Santo Tomas', departamentoCodigo: '08' },
  { codigo: '08758', nombre: 'Soledad', departamentoCodigo: '08' },
  { codigo: '08770', nombre: 'Suan', departamentoCodigo: '08' },
  { codigo: '08832', nombre: 'Tubara', departamentoCodigo: '08' },
  { codigo: '08849', nombre: 'Usiacuri', departamentoCodigo: '08' },
  { codigo: '11001', nombre: 'Bogota D.C', departamentoCodigo: '11' },
  { codigo: '13001', nombre: 'Cartagena', departamentoCodigo: '13' },
  { codigo: '13006', nombre: 'Achi', departamentoCodigo: '13' },
  { codigo: '13030', nombre: 'Altos del Rosario', departamentoCodigo: '13' },
  { codigo: '13042', nombre: 'Arenal', departamentoCodigo: '13' },
  { codigo: '13052', nombre: 'Arjona', departamentoCodigo: '13' },
  { codigo: '13062', nombre: 'Arroyohondo', departamentoCodigo: '13' },
  { codigo: '13074', nombre: 'Barranco de Loba', departamentoCodigo: '13' },
  { codigo: '13140', nombre: 'Calamar - Bolivar', departamentoCodigo: '13' },
  { codigo: '13160', nombre: 'Cantagallo', departamentoCodigo: '13' },
  { codigo: '13188', nombre: 'Cicuco', departamentoCodigo: '13' },
  { codigo: '13212', nombre: 'Cordoba - Bolivar', departamentoCodigo: '13' },
  { codigo: '13222', nombre: 'Clemencia', departamentoCodigo: '13' },
  { codigo: '13244', nombre: 'El Carmen de Bolivar', departamentoCodigo: '13' },
  { codigo: '13248', nombre: 'El Guamo', departamentoCodigo: '13' },
  { codigo: '13268', nombre: 'El Penon - Bolivar', departamentoCodigo: '13' },
  { codigo: '13300', nombre: 'Hatillo de Loba', departamentoCodigo: '13' },
  { codigo: '13430', nombre: 'Magangue', departamentoCodigo: '13' },
  { codigo: '13433', nombre: 'Mahates', departamentoCodigo: '13' },
  { codigo: '13440', nombre: 'Margarita', departamentoCodigo: '13' },
  { codigo: '13442', nombre: 'Maria la Baja', departamentoCodigo: '13' },
  { codigo: '13458', nombre: 'Montecristo', departamentoCodigo: '13' },
  { codigo: '13468', nombre: 'Mompos', departamentoCodigo: '13' },
  { codigo: '13473', nombre: 'Morales - Bolivar', departamentoCodigo: '13' },
  { codigo: '13490', nombre: 'Norosi', departamentoCodigo: '13' },
  { codigo: '13549', nombre: 'Pinillos', departamentoCodigo: '13' },
  { codigo: '13580', nombre: 'Regidor', departamentoCodigo: '13' },
  { codigo: '13600', nombre: 'Rio Viejo', departamentoCodigo: '13' },
  { codigo: '13620', nombre: 'San Cristobal', departamentoCodigo: '13' },
  { codigo: '13647', nombre: 'San Estanislao', departamentoCodigo: '13' },
  { codigo: '13650', nombre: 'San Fernando', departamentoCodigo: '13' },
  { codigo: '13654', nombre: 'San Jacinto', departamentoCodigo: '13' },
  {
    codigo: '13655',
    nombre: 'San Jacinto del Cauca',
    departamentoCodigo: '13',
  },
  { codigo: '13657', nombre: 'San Juan Nepomuceno', departamentoCodigo: '13' },
  { codigo: '13667', nombre: 'San Martin de Loba', departamentoCodigo: '13' },
  { codigo: '13670', nombre: 'San Pablo - Bolivar', departamentoCodigo: '13' },
  { codigo: '13673', nombre: 'Santa Catalina', departamentoCodigo: '13' },
  { codigo: '13683', nombre: 'Santa Rosa - Bolivar', departamentoCodigo: '13' },
  { codigo: '13688', nombre: 'Santa Rosa del Sur', departamentoCodigo: '13' },
  { codigo: '13744', nombre: 'Simiti', departamentoCodigo: '13' },
  { codigo: '13760', nombre: 'Soplaviento', departamentoCodigo: '13' },
  { codigo: '13780', nombre: 'Talaigua Nuevo', departamentoCodigo: '13' },
  { codigo: '13810', nombre: 'Tiquisio', departamentoCodigo: '13' },
  { codigo: '13836', nombre: 'Turbaco', departamentoCodigo: '13' },
  { codigo: '13838', nombre: 'Turbana', departamentoCodigo: '13' },
  { codigo: '13873', nombre: 'Villanueva - Bolivar', departamentoCodigo: '13' },
  { codigo: '13894', nombre: 'Zambrano', departamentoCodigo: '13' },
  { codigo: '15001', nombre: 'Tunja', departamentoCodigo: '15' },
  { codigo: '15022', nombre: 'Almeida', departamentoCodigo: '15' },
  { codigo: '15047', nombre: 'Aquitania', departamentoCodigo: '15' },
  { codigo: '15051', nombre: 'Arcabuco', departamentoCodigo: '15' },
  { codigo: '15087', nombre: 'Belen - Boyaca', departamentoCodigo: '15' },
  { codigo: '15090', nombre: 'Berbeo', departamentoCodigo: '15' },
  { codigo: '15092', nombre: 'Beteitiva', departamentoCodigo: '15' },
  { codigo: '15097', nombre: 'Boavita', departamentoCodigo: '15' },
  { codigo: '15104', nombre: 'Boyaca', departamentoCodigo: '15' },
  { codigo: '15106', nombre: 'Briceno - Boyaca', departamentoCodigo: '15' },
  { codigo: '15109', nombre: 'Buenavista - Boyaca', departamentoCodigo: '15' },
  { codigo: '15114', nombre: 'Busbanza', departamentoCodigo: '15' },
  { codigo: '15131', nombre: 'Caldas - Boyaca', departamentoCodigo: '15' },
  { codigo: '15135', nombre: 'Campohermoso', departamentoCodigo: '15' },
  { codigo: '15162', nombre: 'Cerinza', departamentoCodigo: '15' },
  { codigo: '15172', nombre: 'Chinavita', departamentoCodigo: '15' },
  { codigo: '15176', nombre: 'Chiquinquira', departamentoCodigo: '15' },
  { codigo: '15180', nombre: 'Chiscas', departamentoCodigo: '15' },
  { codigo: '15183', nombre: 'Chita', departamentoCodigo: '15' },
  { codigo: '15185', nombre: 'Chitaraque', departamentoCodigo: '15' },
  { codigo: '15187', nombre: 'Chivata', departamentoCodigo: '15' },
  { codigo: '15189', nombre: 'Cienega - Boyaca', departamentoCodigo: '15' },
  { codigo: '15204', nombre: 'Combita', departamentoCodigo: '15' },
  { codigo: '15212', nombre: 'Coper', departamentoCodigo: '15' },
  { codigo: '15215', nombre: 'Corrales', departamentoCodigo: '15' },
  { codigo: '15218', nombre: 'Covarachia', departamentoCodigo: '15' },
  { codigo: '15223', nombre: 'Cubara', departamentoCodigo: '15' },
  { codigo: '15224', nombre: 'Cucaita', departamentoCodigo: '15' },
  { codigo: '15226', nombre: 'Cuitiva', departamentoCodigo: '15' },
  { codigo: '15232', nombre: 'Chiquiza', departamentoCodigo: '15' },
  { codigo: '15236', nombre: 'Chivor', departamentoCodigo: '15' },
  { codigo: '15238', nombre: 'Duitama', departamentoCodigo: '15' },
  { codigo: '15244', nombre: 'El Cocuy', departamentoCodigo: '15' },
  { codigo: '15248', nombre: 'El Espino', departamentoCodigo: '15' },
  { codigo: '15272', nombre: 'Firavitoba', departamentoCodigo: '15' },
  { codigo: '15276', nombre: 'Floresta', departamentoCodigo: '15' },
  { codigo: '15293', nombre: 'Gachantiva', departamentoCodigo: '15' },
  { codigo: '15296', nombre: 'Gameza', departamentoCodigo: '15' },
  { codigo: '15299', nombre: 'Garagoa', departamentoCodigo: '15' },
  { codigo: '15317', nombre: 'Guacamayas', departamentoCodigo: '15' },
  { codigo: '15322', nombre: 'Guateque', departamentoCodigo: '15' },
  { codigo: '15325', nombre: 'Guayata', departamentoCodigo: '15' },
  { codigo: '15332', nombre: 'Guican', departamentoCodigo: '15' },
  { codigo: '15362', nombre: 'Iza', departamentoCodigo: '15' },
  { codigo: '15367', nombre: 'Jenesano', departamentoCodigo: '15' },
  { codigo: '15368', nombre: 'Jerico - Boyaca', departamentoCodigo: '15' },
  { codigo: '15377', nombre: 'Labranzagrande', departamentoCodigo: '15' },
  { codigo: '15380', nombre: 'La Capilla', departamentoCodigo: '15' },
  { codigo: '15401', nombre: 'La Victoria - Boyaca', departamentoCodigo: '15' },
  { codigo: '15403', nombre: 'La Uvita', departamentoCodigo: '15' },
  { codigo: '15407', nombre: 'Villa de Leyva', departamentoCodigo: '15' },
  { codigo: '15425', nombre: 'Macanal', departamentoCodigo: '15' },
  { codigo: '15442', nombre: 'Maripi', departamentoCodigo: '15' },
  { codigo: '15455', nombre: 'Miraflores - Boyaca', departamentoCodigo: '15' },
  { codigo: '15464', nombre: 'Mongua', departamentoCodigo: '15' },
  { codigo: '15466', nombre: 'Mongui', departamentoCodigo: '15' },
  { codigo: '15469', nombre: 'Moniquira', departamentoCodigo: '15' },
  { codigo: '15476', nombre: 'Motavita', departamentoCodigo: '15' },
  { codigo: '15480', nombre: 'Muzo', departamentoCodigo: '15' },
  { codigo: '15491', nombre: 'Nobsa', departamentoCodigo: '15' },
  { codigo: '15494', nombre: 'Nuevo Colon', departamentoCodigo: '15' },
  { codigo: '15500', nombre: 'Oicata', departamentoCodigo: '15' },
  { codigo: '15507', nombre: 'Otanche', departamentoCodigo: '15' },
  { codigo: '15511', nombre: 'Pachavita', departamentoCodigo: '15' },
  { codigo: '15514', nombre: 'Paez - Boyaca', departamentoCodigo: '15' },
  { codigo: '15516', nombre: 'Paipa', departamentoCodigo: '15' },
  { codigo: '15518', nombre: 'Pajarito', departamentoCodigo: '15' },
  { codigo: '15522', nombre: 'Panqueba', departamentoCodigo: '15' },
  { codigo: '15531', nombre: 'Pauna', departamentoCodigo: '15' },
  { codigo: '15533', nombre: 'Paya', departamentoCodigo: '15' },
  { codigo: '15537', nombre: 'Paz de Rio', departamentoCodigo: '15' },
  { codigo: '15542', nombre: 'Pesca', departamentoCodigo: '15' },
  { codigo: '15550', nombre: 'Pisba', departamentoCodigo: '15' },
  { codigo: '15572', nombre: 'Puerto Boyaca', departamentoCodigo: '15' },
  { codigo: '15580', nombre: 'Quipama', departamentoCodigo: '15' },
  { codigo: '15599', nombre: 'Ramiriqui', departamentoCodigo: '15' },
  { codigo: '15600', nombre: 'Raquira', departamentoCodigo: '15' },
  { codigo: '15621', nombre: 'Rondon', departamentoCodigo: '15' },
  { codigo: '15632', nombre: 'Saboya', departamentoCodigo: '15' },
  { codigo: '15638', nombre: 'Sachica', departamentoCodigo: '15' },
  { codigo: '15646', nombre: 'Samaca', departamentoCodigo: '15' },
  { codigo: '15660', nombre: 'San Eduardo', departamentoCodigo: '15' },
  { codigo: '15664', nombre: 'San Jose de Pare', departamentoCodigo: '15' },
  { codigo: '15667', nombre: 'San Luis de Gaceno', departamentoCodigo: '15' },
  { codigo: '15673', nombre: 'San Mateo', departamentoCodigo: '15' },
  { codigo: '15676', nombre: 'San Miguel de Sema', departamentoCodigo: '15' },
  { codigo: '15681', nombre: 'San Pablo de Borbur', departamentoCodigo: '15' },
  { codigo: '15686', nombre: 'Santana', departamentoCodigo: '15' },
  { codigo: '15690', nombre: 'Santa Maria - Boyaca', departamentoCodigo: '15' },
  {
    codigo: '15693',
    nombre: 'Santa Rosa de Viterbo',
    departamentoCodigo: '15',
  },
  { codigo: '15696', nombre: 'Santa Sofia', departamentoCodigo: '15' },
  { codigo: '15720', nombre: 'Sativanorte', departamentoCodigo: '15' },
  { codigo: '15723', nombre: 'Sativasur', departamentoCodigo: '15' },
  { codigo: '15740', nombre: 'Siachoque', departamentoCodigo: '15' },
  { codigo: '15753', nombre: 'Soata', departamentoCodigo: '15' },
  { codigo: '15755', nombre: 'Socota', departamentoCodigo: '15' },
  { codigo: '15757', nombre: 'Socha', departamentoCodigo: '15' },
  { codigo: '15759', nombre: 'Sogamoso', departamentoCodigo: '15' },
  { codigo: '15761', nombre: 'Somondoco', departamentoCodigo: '15' },
  { codigo: '15762', nombre: 'Sora', departamentoCodigo: '15' },
  { codigo: '15763', nombre: 'Sotaquira', departamentoCodigo: '15' },
  { codigo: '15764', nombre: 'Soraca', departamentoCodigo: '15' },
  { codigo: '15774', nombre: 'Susacon', departamentoCodigo: '15' },
  { codigo: '15776', nombre: 'Sutamarchan', departamentoCodigo: '15' },
  { codigo: '15778', nombre: 'Sutatenza', departamentoCodigo: '15' },
  { codigo: '15790', nombre: 'Tasco', departamentoCodigo: '15' },
  { codigo: '15798', nombre: 'Tenza', departamentoCodigo: '15' },
  { codigo: '15804', nombre: 'Tibana', departamentoCodigo: '15' },
  { codigo: '15806', nombre: 'Tibasosa', departamentoCodigo: '15' },
  { codigo: '15808', nombre: 'Tinjaca', departamentoCodigo: '15' },
  { codigo: '15810', nombre: 'Tipacoque', departamentoCodigo: '15' },
  { codigo: '15814', nombre: 'Toca', departamentoCodigo: '15' },
  { codigo: '15816', nombre: 'Togui', departamentoCodigo: '15' },
  { codigo: '15820', nombre: 'Topaga', departamentoCodigo: '15' },
  { codigo: '15822', nombre: 'Tota', departamentoCodigo: '15' },
  { codigo: '15832', nombre: 'Tunungua', departamentoCodigo: '15' },
  { codigo: '15835', nombre: 'Turmeque', departamentoCodigo: '15' },
  { codigo: '15837', nombre: 'Tuta', departamentoCodigo: '15' },
  { codigo: '15839', nombre: 'Tutaza', departamentoCodigo: '15' },
  { codigo: '15842', nombre: 'Umbita', departamentoCodigo: '15' },
  { codigo: '15861', nombre: 'Ventaquemada', departamentoCodigo: '15' },
  { codigo: '15879', nombre: 'Viracacha', departamentoCodigo: '15' },
  { codigo: '15897', nombre: 'Zetaquira', departamentoCodigo: '15' },
  { codigo: '17001', nombre: 'Manizales', departamentoCodigo: '17' },
  { codigo: '17013', nombre: 'Aguadas', departamentoCodigo: '17' },
  { codigo: '17042', nombre: 'Anserma', departamentoCodigo: '17' },
  { codigo: '17050', nombre: 'Aranzazu', departamentoCodigo: '17' },
  { codigo: '17088', nombre: 'Belalcazar', departamentoCodigo: '17' },
  { codigo: '17174', nombre: 'Chinchina', departamentoCodigo: '17' },
  { codigo: '17272', nombre: 'Filadelfia', departamentoCodigo: '17' },
  { codigo: '17380', nombre: 'La Dorada', departamentoCodigo: '17' },
  { codigo: '17388', nombre: 'La Merced', departamentoCodigo: '17' },
  { codigo: '17433', nombre: 'Manzanares', departamentoCodigo: '17' },
  { codigo: '17442', nombre: 'Marmato', departamentoCodigo: '17' },
  { codigo: '17444', nombre: 'Marquetalia', departamentoCodigo: '17' },
  { codigo: '17446', nombre: 'Marulanda', departamentoCodigo: '17' },
  { codigo: '17486', nombre: 'Neira', departamentoCodigo: '17' },
  { codigo: '17495', nombre: 'Norcasia', departamentoCodigo: '17' },
  { codigo: '17513', nombre: 'Pacora', departamentoCodigo: '17' },
  { codigo: '17524', nombre: 'Palestina - Caldas', departamentoCodigo: '17' },
  { codigo: '17541', nombre: 'Pensilvania', departamentoCodigo: '17' },
  { codigo: '17614', nombre: 'Riosucio - Caldas', departamentoCodigo: '17' },
  { codigo: '17616', nombre: 'Risaralda', departamentoCodigo: '17' },
  { codigo: '17653', nombre: 'Salamina - Caldas', departamentoCodigo: '17' },
  { codigo: '17662', nombre: 'Samana', departamentoCodigo: '17' },
  { codigo: '17665', nombre: 'San Jose', departamentoCodigo: '17' },
  { codigo: '17777', nombre: 'Supia', departamentoCodigo: '17' },
  { codigo: '17867', nombre: 'Victoria', departamentoCodigo: '17' },
  { codigo: '17873', nombre: 'Villamaria', departamentoCodigo: '17' },
  { codigo: '17877', nombre: 'Viterbo', departamentoCodigo: '17' },
  { codigo: '18001', nombre: 'Florencia - Caqueta', departamentoCodigo: '18' },
  { codigo: '18029', nombre: 'Albania - Caqueta', departamentoCodigo: '18' },
  {
    codigo: '18094',
    nombre: 'Belen de los Andaquies',
    departamentoCodigo: '18',
  },
  { codigo: '18150', nombre: 'Cartagena del Chaira', departamentoCodigo: '18' },
  { codigo: '18205', nombre: 'Curillo', departamentoCodigo: '18' },
  { codigo: '18247', nombre: 'El Doncello', departamentoCodigo: '18' },
  { codigo: '18256', nombre: 'El Paujil', departamentoCodigo: '18' },
  { codigo: '18410', nombre: 'La Montanita', departamentoCodigo: '18' },
  { codigo: '18460', nombre: 'Milan', departamentoCodigo: '18' },
  { codigo: '18479', nombre: 'Morelia', departamentoCodigo: '18' },
  {
    codigo: '18592',
    nombre: 'Puerto Rico - Caqueta',
    departamentoCodigo: '18',
  },
  { codigo: '18610', nombre: 'San Jose del Fragua', departamentoCodigo: '18' },
  {
    codigo: '18753',
    nombre: 'San Vicente del Caguan',
    departamentoCodigo: '18',
  },
  { codigo: '18756', nombre: 'Solano', departamentoCodigo: '18' },
  { codigo: '18785', nombre: 'Solita', departamentoCodigo: '18' },
  { codigo: '18860', nombre: 'Valparaiso - Caqueta', departamentoCodigo: '18' },
  { codigo: '19001', nombre: 'Popayan', departamentoCodigo: '19' },
  { codigo: '19022', nombre: 'Almaguer', departamentoCodigo: '19' },
  { codigo: '19050', nombre: 'Argelia - Cauca', departamentoCodigo: '19' },
  { codigo: '19075', nombre: 'Balboa - Cauca', departamentoCodigo: '19' },
  { codigo: '19100', nombre: 'Bolivar - Cauca', departamentoCodigo: '19' },
  { codigo: '19110', nombre: 'Buenos Aires', departamentoCodigo: '19' },
  { codigo: '19130', nombre: 'Cajibio', departamentoCodigo: '19' },
  { codigo: '19137', nombre: 'Caldono', departamentoCodigo: '19' },
  { codigo: '19142', nombre: 'Caloto', departamentoCodigo: '19' },
  { codigo: '19212', nombre: 'Corinto', departamentoCodigo: '19' },
  { codigo: '19256', nombre: 'El Tambo - Cauca', departamentoCodigo: '19' },
  { codigo: '19290', nombre: 'Florencia - Cauca', departamentoCodigo: '19' },
  { codigo: '19300', nombre: 'Guachene', departamentoCodigo: '19' },
  { codigo: '19318', nombre: 'Guapi', departamentoCodigo: '19' },
  { codigo: '19355', nombre: 'Inza', departamentoCodigo: '19' },
  { codigo: '19364', nombre: 'Jambalo', departamentoCodigo: '19' },
  { codigo: '19392', nombre: 'La Sierra', departamentoCodigo: '19' },
  { codigo: '19397', nombre: 'La Vega - Cauca', departamentoCodigo: '19' },
  { codigo: '19418', nombre: 'Lopez', departamentoCodigo: '19' },
  { codigo: '19450', nombre: 'Mercaderes', departamentoCodigo: '19' },
  { codigo: '19455', nombre: 'Miranda', departamentoCodigo: '19' },
  { codigo: '19473', nombre: 'Morales - Cauca', departamentoCodigo: '19' },
  { codigo: '19513', nombre: 'Padilla', departamentoCodigo: '19' },
  { codigo: '19517', nombre: 'Paez - Cauca', departamentoCodigo: '19' },
  { codigo: '19532', nombre: 'Patia', departamentoCodigo: '19' },
  { codigo: '19533', nombre: 'Piamonte', departamentoCodigo: '19' },
  { codigo: '19548', nombre: 'Piendamo', departamentoCodigo: '19' },
  { codigo: '19573', nombre: 'Puerto Tejada', departamentoCodigo: '19' },
  { codigo: '19585', nombre: 'Purace', departamentoCodigo: '19' },
  { codigo: '19622', nombre: 'Rosas', departamentoCodigo: '19' },
  { codigo: '19693', nombre: 'San Sebastian', departamentoCodigo: '19' },
  {
    codigo: '19698',
    nombre: 'Santander de Quilichao',
    departamentoCodigo: '19',
  },
  { codigo: '19701', nombre: 'Santa Rosa - Cauca', departamentoCodigo: '19' },
  { codigo: '19743', nombre: 'Silvia', departamentoCodigo: '19' },
  { codigo: '19760', nombre: 'Sotara', departamentoCodigo: '19' },
  { codigo: '19780', nombre: 'Suarez - Cauca', departamentoCodigo: '19' },
  { codigo: '19785', nombre: 'Sucre - Cauca', departamentoCodigo: '19' },
  { codigo: '19807', nombre: 'Timbio', departamentoCodigo: '19' },
  { codigo: '19809', nombre: 'Timbiqui', departamentoCodigo: '19' },
  { codigo: '19821', nombre: 'Toribio', departamentoCodigo: '19' },
  { codigo: '19824', nombre: 'Totoro', departamentoCodigo: '19' },
  { codigo: '19845', nombre: 'Villa Rica', departamentoCodigo: '19' },
  { codigo: '20001', nombre: 'Valledupar', departamentoCodigo: '20' },
  { codigo: '20011', nombre: 'Aguachica', departamentoCodigo: '20' },
  { codigo: '20013', nombre: 'Agustin Codazzi', departamentoCodigo: '20' },
  { codigo: '20032', nombre: 'Astrea', departamentoCodigo: '20' },
  { codigo: '20045', nombre: 'Becerril', departamentoCodigo: '20' },
  { codigo: '20060', nombre: 'Bosconia', departamentoCodigo: '20' },
  { codigo: '20175', nombre: 'Chimichagua', departamentoCodigo: '20' },
  { codigo: '20178', nombre: 'Chiriguana', departamentoCodigo: '20' },
  { codigo: '20228', nombre: 'Curumani', departamentoCodigo: '20' },
  { codigo: '20238', nombre: 'El Copey', departamentoCodigo: '20' },
  { codigo: '20250', nombre: 'El Paso', departamentoCodigo: '20' },
  { codigo: '20295', nombre: 'Gamarra', departamentoCodigo: '20' },
  { codigo: '20310', nombre: 'Gonzalez', departamentoCodigo: '20' },
  { codigo: '20383', nombre: 'La Gloria', departamentoCodigo: '20' },
  { codigo: '20400', nombre: 'La Jagua de Ibirico', departamentoCodigo: '20' },
  { codigo: '20443', nombre: 'Manaure - Cesar', departamentoCodigo: '20' },
  { codigo: '20517', nombre: 'Pailitas', departamentoCodigo: '20' },
  { codigo: '20550', nombre: 'Pelaya', departamentoCodigo: '20' },
  { codigo: '20570', nombre: 'Pueblo Bello', departamentoCodigo: '20' },
  { codigo: '20614', nombre: 'Rio de Oro', departamentoCodigo: '20' },
  { codigo: '20621', nombre: 'La Paz - Cesar', departamentoCodigo: '20' },
  { codigo: '20710', nombre: 'San Alberto', departamentoCodigo: '20' },
  { codigo: '20750', nombre: 'San Diego', departamentoCodigo: '20' },
  { codigo: '20770', nombre: 'San Martin - Cesar', departamentoCodigo: '20' },
  { codigo: '20787', nombre: 'Tamalameque', departamentoCodigo: '20' },
  { codigo: '23001', nombre: 'Monteria', departamentoCodigo: '23' },
  { codigo: '23068', nombre: 'Ayapel', departamentoCodigo: '23' },
  { codigo: '23079', nombre: 'Buenavista - Cordoba', departamentoCodigo: '23' },
  { codigo: '23090', nombre: 'Canalete', departamentoCodigo: '23' },
  { codigo: '23162', nombre: 'Cerete', departamentoCodigo: '23' },
  { codigo: '23168', nombre: 'Chima', departamentoCodigo: '23' },
  { codigo: '23182', nombre: 'Chinu', departamentoCodigo: '23' },
  { codigo: '23189', nombre: 'Cienaga de Oro', departamentoCodigo: '23' },
  { codigo: '23300', nombre: 'Cotorra', departamentoCodigo: '23' },
  { codigo: '23350', nombre: 'La Apartada', departamentoCodigo: '23' },
  { codigo: '23417', nombre: 'Lorica', departamentoCodigo: '23' },
  { codigo: '23419', nombre: 'Los Cordobas', departamentoCodigo: '23' },
  { codigo: '23464', nombre: 'Momil', departamentoCodigo: '23' },
  { codigo: '23466', nombre: 'Montelibano', departamentoCodigo: '23' },
  { codigo: '23500', nombre: 'Monitos', departamentoCodigo: '23' },
  { codigo: '23555', nombre: 'Planeta Rica', departamentoCodigo: '23' },
  { codigo: '23570', nombre: 'Pueblo Nuevo', departamentoCodigo: '23' },
  { codigo: '23574', nombre: 'Puerto Escondido', departamentoCodigo: '23' },
  { codigo: '23580', nombre: 'Puerto Libertador', departamentoCodigo: '23' },
  { codigo: '23586', nombre: 'Purisima', departamentoCodigo: '23' },
  { codigo: '23660', nombre: 'Sahagun', departamentoCodigo: '23' },
  { codigo: '23670', nombre: 'San Andres Sotavento', departamentoCodigo: '23' },
  { codigo: '23672', nombre: 'San Antero', departamentoCodigo: '23' },
  {
    codigo: '23675',
    nombre: 'San Bernardo del Viento',
    departamentoCodigo: '23',
  },
  { codigo: '23678', nombre: 'San Carlos - Cordoba', departamentoCodigo: '23' },
  { codigo: '23682', nombre: 'San Jose de Ure', departamentoCodigo: '23' },
  { codigo: '23686', nombre: 'San Pelayo', departamentoCodigo: '23' },
  { codigo: '23807', nombre: 'Tierralta', departamentoCodigo: '23' },
  { codigo: '23815', nombre: 'Tuchin', departamentoCodigo: '23' },
  { codigo: '23855', nombre: 'Valencia', departamentoCodigo: '23' },
  { codigo: '25001', nombre: 'Agua de Dios', departamentoCodigo: '25' },
  { codigo: '25019', nombre: 'Alban - Cundinamarca', departamentoCodigo: '25' },
  { codigo: '25035', nombre: 'Anapoima', departamentoCodigo: '25' },
  { codigo: '25040', nombre: 'Anolaima', departamentoCodigo: '25' },
  { codigo: '25053', nombre: 'Arbelaez', departamentoCodigo: '25' },
  { codigo: '25086', nombre: 'Beltran', departamentoCodigo: '25' },
  { codigo: '25095', nombre: 'Bituima', departamentoCodigo: '25' },
  { codigo: '25099', nombre: 'Bojaca', departamentoCodigo: '25' },
  {
    codigo: '25120',
    nombre: 'Cabrera - Cundinamarca',
    departamentoCodigo: '25',
  },
  { codigo: '25123', nombre: 'Cachipay', departamentoCodigo: '25' },
  { codigo: '25126', nombre: 'Cajica', departamentoCodigo: '25' },
  { codigo: '25148', nombre: 'Caparrapi', departamentoCodigo: '25' },
  { codigo: '25151', nombre: 'Caqueza', departamentoCodigo: '25' },
  { codigo: '25154', nombre: 'Carmen de Carupa', departamentoCodigo: '25' },
  { codigo: '25168', nombre: 'Chaguani', departamentoCodigo: '25' },
  { codigo: '25175', nombre: 'Chia', departamentoCodigo: '25' },
  { codigo: '25178', nombre: 'Chipaque', departamentoCodigo: '25' },
  { codigo: '25181', nombre: 'Choachi', departamentoCodigo: '25' },
  { codigo: '25183', nombre: 'Choconta', departamentoCodigo: '25' },
  { codigo: '25200', nombre: 'Cogua', departamentoCodigo: '25' },
  { codigo: '25214', nombre: 'Cota', departamentoCodigo: '25' },
  { codigo: '25224', nombre: 'Cucunuba', departamentoCodigo: '25' },
  { codigo: '25245', nombre: 'El Colegio', departamentoCodigo: '25' },
  {
    codigo: '25258',
    nombre: 'El Penon - Cundinamarca',
    departamentoCodigo: '25',
  },
  { codigo: '25260', nombre: 'El Rosal', departamentoCodigo: '25' },
  { codigo: '25269', nombre: 'Facatativa', departamentoCodigo: '25' },
  { codigo: '25279', nombre: 'Fomeque', departamentoCodigo: '25' },
  { codigo: '25281', nombre: 'Fosca', departamentoCodigo: '25' },
  { codigo: '25286', nombre: 'Funza', departamentoCodigo: '25' },
  { codigo: '25288', nombre: 'Fuquene', departamentoCodigo: '25' },
  { codigo: '25290', nombre: 'Fusagasuga', departamentoCodigo: '25' },
  { codigo: '25293', nombre: 'Gachala', departamentoCodigo: '25' },
  { codigo: '25295', nombre: 'Gachancipa', departamentoCodigo: '25' },
  { codigo: '25297', nombre: 'Gacheta', departamentoCodigo: '25' },
  { codigo: '25299', nombre: 'Gama', departamentoCodigo: '25' },
  { codigo: '25307', nombre: 'Girardot', departamentoCodigo: '25' },
  {
    codigo: '25312',
    nombre: 'Granada - Cundinamarca',
    departamentoCodigo: '25',
  },
  { codigo: '25317', nombre: 'Guacheta', departamentoCodigo: '25' },
  { codigo: '25320', nombre: 'Guaduas', departamentoCodigo: '25' },
  { codigo: '25322', nombre: 'Guasca', departamentoCodigo: '25' },
  { codigo: '25324', nombre: 'Guataqui', departamentoCodigo: '25' },
  { codigo: '25326', nombre: 'Guatavita', departamentoCodigo: '25' },
  { codigo: '25328', nombre: 'Guayabal de Siquima', departamentoCodigo: '25' },
  { codigo: '25335', nombre: 'Guayabetal', departamentoCodigo: '25' },
  { codigo: '25339', nombre: 'Gutierrez', departamentoCodigo: '25' },
  { codigo: '25368', nombre: 'Jerusalen', departamentoCodigo: '25' },
  { codigo: '25372', nombre: 'Junin', departamentoCodigo: '25' },
  { codigo: '25377', nombre: 'La Calera', departamentoCodigo: '25' },
  { codigo: '25386', nombre: 'La Mesa', departamentoCodigo: '25' },
  { codigo: '25394', nombre: 'La Palma', departamentoCodigo: '25' },
  { codigo: '25398', nombre: 'La Pena', departamentoCodigo: '25' },
  {
    codigo: '25402',
    nombre: 'La Vega - Cundinamarca',
    departamentoCodigo: '25',
  },
  { codigo: '25407', nombre: 'Lenguazaque', departamentoCodigo: '25' },
  { codigo: '25426', nombre: 'Macheta', departamentoCodigo: '25' },
  { codigo: '25430', nombre: 'Madrid', departamentoCodigo: '25' },
  { codigo: '25436', nombre: 'Manta', departamentoCodigo: '25' },
  { codigo: '25438', nombre: 'Medina', departamentoCodigo: '25' },
  {
    codigo: '25473',
    nombre: 'Mosquera - Cundinamarca',
    departamentoCodigo: '25',
  },
  {
    codigo: '25483',
    nombre: 'Narino - Cundinamarca',
    departamentoCodigo: '25',
  },
  { codigo: '25486', nombre: 'Nemocon', departamentoCodigo: '25' },
  { codigo: '25488', nombre: 'Nilo', departamentoCodigo: '25' },
  { codigo: '25489', nombre: 'Nimaima', departamentoCodigo: '25' },
  { codigo: '25491', nombre: 'Nocaima', departamentoCodigo: '25' },
  {
    codigo: '25506',
    nombre: 'Venecia - Cundinamarca',
    departamentoCodigo: '25',
  },
  { codigo: '25513', nombre: 'Pacho', departamentoCodigo: '25' },
  { codigo: '25518', nombre: 'Paime', departamentoCodigo: '25' },
  { codigo: '25524', nombre: 'Pandi', departamentoCodigo: '25' },
  { codigo: '25530', nombre: 'Paratebueno', departamentoCodigo: '25' },
  { codigo: '25535', nombre: 'Pasca', departamentoCodigo: '25' },
  { codigo: '25572', nombre: 'Puerto Salgar', departamentoCodigo: '25' },
  { codigo: '25580', nombre: 'Puli', departamentoCodigo: '25' },
  { codigo: '25592', nombre: 'Quebradanegra', departamentoCodigo: '25' },
  { codigo: '25594', nombre: 'Quetame', departamentoCodigo: '25' },
  { codigo: '25596', nombre: 'Quipile', departamentoCodigo: '25' },
  { codigo: '25599', nombre: 'Apulo', departamentoCodigo: '25' },
  {
    codigo: '25612',
    nombre: 'Ricaurte - Cundinamarca',
    departamentoCodigo: '25',
  },
  {
    codigo: '25645',
    nombre: 'San Antonio del Tequendama',
    departamentoCodigo: '25',
  },
  {
    codigo: '25649',
    nombre: 'San Bernardo - Cundinamarca',
    departamentoCodigo: '25',
  },
  {
    codigo: '25653',
    nombre: 'San Cayetano - Cundinamarca',
    departamentoCodigo: '25',
  },
  {
    codigo: '25658',
    nombre: 'San Francisco - Cundinamarca',
    departamentoCodigo: '25',
  },
  { codigo: '25662', nombre: 'San Juan de Rio Seco', departamentoCodigo: '25' },
  { codigo: '25718', nombre: 'Sasaima', departamentoCodigo: '25' },
  { codigo: '25736', nombre: 'Sesquile', departamentoCodigo: '25' },
  { codigo: '25740', nombre: 'Sibate', departamentoCodigo: '25' },
  { codigo: '25743', nombre: 'Silvania', departamentoCodigo: '25' },
  { codigo: '25745', nombre: 'Simijaca', departamentoCodigo: '25' },
  { codigo: '25754', nombre: 'Soacha', departamentoCodigo: '25' },
  { codigo: '25758', nombre: 'Sopo', departamentoCodigo: '25' },
  { codigo: '25769', nombre: 'Subachoque', departamentoCodigo: '25' },
  { codigo: '25772', nombre: 'Suesca', departamentoCodigo: '25' },
  { codigo: '25777', nombre: 'Supata', departamentoCodigo: '25' },
  { codigo: '25779', nombre: 'Susa', departamentoCodigo: '25' },
  { codigo: '25781', nombre: 'Sutatausa', departamentoCodigo: '25' },
  { codigo: '25785', nombre: 'Tabio', departamentoCodigo: '25' },
  { codigo: '25793', nombre: 'Tausa', departamentoCodigo: '25' },
  { codigo: '25797', nombre: 'Tena', departamentoCodigo: '25' },
  { codigo: '25799', nombre: 'Tenjo', departamentoCodigo: '25' },
  { codigo: '25805', nombre: 'Tibacuy', departamentoCodigo: '25' },
  { codigo: '25807', nombre: 'Tibirita', departamentoCodigo: '25' },
  { codigo: '25815', nombre: 'Tocaima', departamentoCodigo: '25' },
  { codigo: '25817', nombre: 'Tocancipa', departamentoCodigo: '25' },
  { codigo: '25823', nombre: 'Topaipi', departamentoCodigo: '25' },
  { codigo: '25839', nombre: 'Ubala', departamentoCodigo: '25' },
  { codigo: '25841', nombre: 'Ubaque', departamentoCodigo: '25' },
  {
    codigo: '25843',
    nombre: 'Villa de San Diego de Ubate',
    departamentoCodigo: '25',
  },
  { codigo: '25845', nombre: 'Une', departamentoCodigo: '25' },
  { codigo: '25851', nombre: 'Utica', departamentoCodigo: '25' },
  { codigo: '25862', nombre: 'Vergara', departamentoCodigo: '25' },
  { codigo: '25867', nombre: 'Viani', departamentoCodigo: '25' },
  { codigo: '25871', nombre: 'Villagomez', departamentoCodigo: '25' },
  { codigo: '25873', nombre: 'Villapinzon', departamentoCodigo: '25' },
  { codigo: '25875', nombre: 'Villeta', departamentoCodigo: '25' },
  { codigo: '25878', nombre: 'Viota', departamentoCodigo: '25' },
  { codigo: '25885', nombre: 'Yacopi', departamentoCodigo: '25' },
  { codigo: '25898', nombre: 'Zipacon', departamentoCodigo: '25' },
  { codigo: '25899', nombre: 'Zipaquira', departamentoCodigo: '25' },
  { codigo: '27001', nombre: 'Quibdo', departamentoCodigo: '27' },
  { codigo: '27006', nombre: 'Acandi', departamentoCodigo: '27' },
  { codigo: '27025', nombre: 'Alto Baudo', departamentoCodigo: '27' },
  { codigo: '27050', nombre: 'Atrato', departamentoCodigo: '27' },
  { codigo: '27073', nombre: 'Bagado', departamentoCodigo: '27' },
  { codigo: '27075', nombre: 'Bahia Solano', departamentoCodigo: '27' },
  { codigo: '27077', nombre: 'Bajo Baudo', departamentoCodigo: '27' },
  { codigo: '27086', nombre: 'Belen de Bajira', departamentoCodigo: '27' },
  { codigo: '27099', nombre: 'Bojaya', departamentoCodigo: '27' },
  {
    codigo: '27135',
    nombre: 'El Canton del San Pablo',
    departamentoCodigo: '27',
  },
  { codigo: '27150', nombre: 'Carmen del Darien', departamentoCodigo: '27' },
  { codigo: '27160', nombre: 'Certegui', departamentoCodigo: '27' },
  { codigo: '27205', nombre: 'Condoto', departamentoCodigo: '27' },
  { codigo: '27245', nombre: 'El Carmen de Atrato', departamentoCodigo: '27' },
  {
    codigo: '27250',
    nombre: 'El Litoral del San Juan',
    departamentoCodigo: '27',
  },
  { codigo: '27361', nombre: 'Istmina', departamentoCodigo: '27' },
  { codigo: '27372', nombre: 'Jurado', departamentoCodigo: '27' },
  { codigo: '27413', nombre: 'Lloro', departamentoCodigo: '27' },
  { codigo: '27425', nombre: 'Medio Atrato', departamentoCodigo: '27' },
  { codigo: '27430', nombre: 'Medio Baudo', departamentoCodigo: '27' },
  { codigo: '27450', nombre: 'Medio San Juan', departamentoCodigo: '27' },
  { codigo: '27491', nombre: 'Novita', departamentoCodigo: '27' },
  { codigo: '27495', nombre: 'Nuqui', departamentoCodigo: '27' },
  { codigo: '27580', nombre: 'Rio Iro', departamentoCodigo: '27' },
  { codigo: '27600', nombre: 'Rio Quito', departamentoCodigo: '27' },
  { codigo: '27615', nombre: 'Riosucio - Choco', departamentoCodigo: '27' },
  { codigo: '27660', nombre: 'San Jose del Palmar', departamentoCodigo: '27' },
  { codigo: '27745', nombre: 'Sipi', departamentoCodigo: '27' },
  { codigo: '27787', nombre: 'Tado', departamentoCodigo: '27' },
  { codigo: '27800', nombre: 'Unguia', departamentoCodigo: '27' },
  { codigo: '27810', nombre: 'Union Panamericana', departamentoCodigo: '27' },
  { codigo: '41001', nombre: 'Neiva', departamentoCodigo: '41' },
  { codigo: '41006', nombre: 'Acevedo', departamentoCodigo: '41' },
  { codigo: '41013', nombre: 'Agrado', departamentoCodigo: '41' },
  { codigo: '41016', nombre: 'Aipe', departamentoCodigo: '41' },
  { codigo: '41020', nombre: 'Algeciras', departamentoCodigo: '41' },
  { codigo: '41026', nombre: 'Altamira', departamentoCodigo: '41' },
  { codigo: '41078', nombre: 'Baraya', departamentoCodigo: '41' },
  { codigo: '41132', nombre: 'Campoalegre', departamentoCodigo: '41' },
  { codigo: '41206', nombre: 'Colombia', departamentoCodigo: '41' },
  { codigo: '41244', nombre: 'Elias', departamentoCodigo: '41' },
  { codigo: '41298', nombre: 'Garzon', departamentoCodigo: '41' },
  { codigo: '41306', nombre: 'Gigante', departamentoCodigo: '41' },
  { codigo: '41319', nombre: 'Guadalupe - Huila', departamentoCodigo: '41' },
  { codigo: '41349', nombre: 'Hobo', departamentoCodigo: '41' },
  { codigo: '41357', nombre: 'Iquira', departamentoCodigo: '41' },
  { codigo: '41359', nombre: 'Isnos', departamentoCodigo: '41' },
  { codigo: '41378', nombre: 'La Argentina', departamentoCodigo: '41' },
  { codigo: '41396', nombre: 'La Plata', departamentoCodigo: '41' },
  { codigo: '41483', nombre: 'Nataga', departamentoCodigo: '41' },
  { codigo: '41503', nombre: 'Oporapa', departamentoCodigo: '41' },
  { codigo: '41518', nombre: 'Paicol', departamentoCodigo: '41' },
  { codigo: '41524', nombre: 'Palermo', departamentoCodigo: '41' },
  { codigo: '41530', nombre: 'Palestina - Huila', departamentoCodigo: '41' },
  { codigo: '41548', nombre: 'Pital', departamentoCodigo: '41' },
  { codigo: '41551', nombre: 'Pitalito', departamentoCodigo: '41' },
  { codigo: '41615', nombre: 'Rivera', departamentoCodigo: '41' },
  { codigo: '41660', nombre: 'Saladoblanco', departamentoCodigo: '41' },
  { codigo: '41668', nombre: 'San Agustin', departamentoCodigo: '41' },
  { codigo: '41676', nombre: 'Santa Maria - Huila', departamentoCodigo: '41' },
  { codigo: '41770', nombre: 'Suaza', departamentoCodigo: '41' },
  { codigo: '41791', nombre: 'Tarqui', departamentoCodigo: '41' },
  { codigo: '41797', nombre: 'Tesalia', departamentoCodigo: '41' },
  { codigo: '41799', nombre: 'Tello', departamentoCodigo: '41' },
  { codigo: '41801', nombre: 'Teruel', departamentoCodigo: '41' },
  { codigo: '41807', nombre: 'Timana', departamentoCodigo: '41' },
  { codigo: '41872', nombre: 'Villavieja', departamentoCodigo: '41' },
  { codigo: '41885', nombre: 'Yaguara', departamentoCodigo: '41' },
  { codigo: '44001', nombre: 'Riohacha', departamentoCodigo: '44' },
  { codigo: '44035', nombre: 'Albania - La Guajira', departamentoCodigo: '44' },
  { codigo: '44078', nombre: 'Barrancas', departamentoCodigo: '44' },
  { codigo: '44090', nombre: 'Dibulla', departamentoCodigo: '44' },
  { codigo: '44098', nombre: 'Distraccion', departamentoCodigo: '44' },
  { codigo: '44110', nombre: 'El Molino', departamentoCodigo: '44' },
  { codigo: '44279', nombre: 'Fonseca', departamentoCodigo: '44' },
  { codigo: '44378', nombre: 'Hatonuevo', departamentoCodigo: '44' },
  { codigo: '44420', nombre: 'La Jagua del Pilar', departamentoCodigo: '44' },
  { codigo: '44430', nombre: 'Maicao', departamentoCodigo: '44' },
  { codigo: '44560', nombre: 'Manaure - La Guajira', departamentoCodigo: '44' },
  { codigo: '44650', nombre: 'San Juan del Cesar', departamentoCodigo: '44' },
  { codigo: '44847', nombre: 'Uribia', departamentoCodigo: '44' },
  { codigo: '44855', nombre: 'Urumita', departamentoCodigo: '44' },
  {
    codigo: '44874',
    nombre: 'Villanueva - La Guajira',
    departamentoCodigo: '44',
  },
  { codigo: '47001', nombre: 'Santa Marta', departamentoCodigo: '47' },
  { codigo: '47030', nombre: 'Algarrobo', departamentoCodigo: '47' },
  { codigo: '47053', nombre: 'Aracataca', departamentoCodigo: '47' },
  { codigo: '47058', nombre: 'Ariguani', departamentoCodigo: '47' },
  { codigo: '47161', nombre: 'Cerro San Antonio', departamentoCodigo: '47' },
  { codigo: '47170', nombre: 'Chibolo', departamentoCodigo: '47' },
  { codigo: '47189', nombre: 'Cienaga - Magdalena', departamentoCodigo: '47' },
  {
    codigo: '47205',
    nombre: 'Concordia - Magdalena',
    departamentoCodigo: '47',
  },
  { codigo: '47245', nombre: 'El Banco', departamentoCodigo: '47' },
  { codigo: '47258', nombre: 'El Pinon', departamentoCodigo: '47' },
  { codigo: '47268', nombre: 'El Reten', departamentoCodigo: '47' },
  { codigo: '47288', nombre: 'Fundacion', departamentoCodigo: '47' },
  { codigo: '47318', nombre: 'Guamal - Magdalena', departamentoCodigo: '47' },
  { codigo: '47460', nombre: 'Nueva Granada', departamentoCodigo: '47' },
  { codigo: '47541', nombre: 'Pedraza', departamentoCodigo: '47' },
  { codigo: '47545', nombre: 'Pijino del Carmen', departamentoCodigo: '47' },
  { codigo: '47551', nombre: 'Pivijay', departamentoCodigo: '47' },
  { codigo: '47555', nombre: 'Plato', departamentoCodigo: '47' },
  { codigo: '47570', nombre: 'Puebloviejo', departamentoCodigo: '47' },
  { codigo: '47605', nombre: 'Remolino', departamentoCodigo: '47' },
  { codigo: '47660', nombre: 'Sabanas de San Angel', departamentoCodigo: '47' },
  { codigo: '47675', nombre: 'Salamina - Magdalena', departamentoCodigo: '47' },
  {
    codigo: '47692',
    nombre: 'San Sebastian de Buenavista',
    departamentoCodigo: '47',
  },
  { codigo: '47703', nombre: 'San Zenon', departamentoCodigo: '47' },
  { codigo: '47707', nombre: 'Santa Ana', departamentoCodigo: '47' },
  {
    codigo: '47720',
    nombre: 'Santa Barbara de Pinto',
    departamentoCodigo: '47',
  },
  { codigo: '47745', nombre: 'Sitionuevo', departamentoCodigo: '47' },
  { codigo: '47798', nombre: 'Tenerife', departamentoCodigo: '47' },
  { codigo: '47960', nombre: 'Zapayan', departamentoCodigo: '47' },
  { codigo: '47980', nombre: 'Zona Bananera', departamentoCodigo: '47' },
  { codigo: '50001', nombre: 'Villavicencio', departamentoCodigo: '50' },
  { codigo: '50006', nombre: 'Acacias', departamentoCodigo: '50' },
  { codigo: '50110', nombre: 'Barranca de Upia', departamentoCodigo: '50' },
  { codigo: '50124', nombre: 'Cabuyaro', departamentoCodigo: '50' },
  { codigo: '50150', nombre: 'Castilla la Nueva', departamentoCodigo: '50' },
  { codigo: '50223', nombre: 'Cubarral', departamentoCodigo: '50' },
  { codigo: '50226', nombre: 'Cumaral', departamentoCodigo: '50' },
  { codigo: '50245', nombre: 'El Calvario', departamentoCodigo: '50' },
  { codigo: '50251', nombre: 'El Castillo', departamentoCodigo: '50' },
  { codigo: '50270', nombre: 'El Dorado', departamentoCodigo: '50' },
  { codigo: '50287', nombre: 'Fuente de Oro', departamentoCodigo: '50' },
  { codigo: '50313', nombre: 'Granada - Meta', departamentoCodigo: '50' },
  { codigo: '50318', nombre: 'Guamal - Meta', departamentoCodigo: '50' },
  { codigo: '50325', nombre: 'Mapiripan', departamentoCodigo: '50' },
  { codigo: '50330', nombre: 'Mesetas', departamentoCodigo: '50' },
  { codigo: '50350', nombre: 'La Macarena', departamentoCodigo: '50' },
  { codigo: '50370', nombre: 'Uribe', departamentoCodigo: '50' },
  { codigo: '50400', nombre: 'Lejanias', departamentoCodigo: '50' },
  { codigo: '50450', nombre: 'Puerto Concordia', departamentoCodigo: '50' },
  { codigo: '50568', nombre: 'Puerto Gaitan', departamentoCodigo: '50' },
  { codigo: '50573', nombre: 'Puerto Lopez', departamentoCodigo: '50' },
  { codigo: '50577', nombre: 'Puerto Lleras', departamentoCodigo: '50' },
  { codigo: '50590', nombre: 'Puerto Rico - Meta', departamentoCodigo: '50' },
  { codigo: '50606', nombre: 'Restrepo - Meta', departamentoCodigo: '50' },
  { codigo: '50680', nombre: 'San Carlos de Guaroa', departamentoCodigo: '50' },
  { codigo: '50683', nombre: 'San Juan de Arama', departamentoCodigo: '50' },
  { codigo: '50686', nombre: 'San Juanito', departamentoCodigo: '50' },
  { codigo: '50689', nombre: 'San Martin - Meta', departamentoCodigo: '50' },
  { codigo: '50711', nombre: 'Vistahermosa', departamentoCodigo: '50' },
  { codigo: '52001', nombre: 'Pasto', departamentoCodigo: '52' },
  { codigo: '52019', nombre: 'Alban - Narino', departamentoCodigo: '52' },
  { codigo: '52022', nombre: 'Aldana', departamentoCodigo: '52' },
  { codigo: '52036', nombre: 'Ancuya', departamentoCodigo: '52' },
  { codigo: '52051', nombre: 'Arboleda', departamentoCodigo: '52' },
  { codigo: '52079', nombre: 'Barbacoas', departamentoCodigo: '52' },
  { codigo: '52083', nombre: 'Belen - Narino', departamentoCodigo: '52' },
  { codigo: '52110', nombre: 'Buesaco', departamentoCodigo: '52' },
  { codigo: '52203', nombre: 'Colon - Narino', departamentoCodigo: '52' },
  { codigo: '52207', nombre: 'Consaca', departamentoCodigo: '52' },
  { codigo: '52210', nombre: 'Contadero', departamentoCodigo: '52' },
  { codigo: '52215', nombre: 'Cordoba - Narino', departamentoCodigo: '52' },
  { codigo: '52224', nombre: 'Cuaspud', departamentoCodigo: '52' },
  { codigo: '52227', nombre: 'Cumbal', departamentoCodigo: '52' },
  { codigo: '52233', nombre: 'Cumbitara', departamentoCodigo: '52' },
  { codigo: '52240', nombre: 'Chachagui', departamentoCodigo: '52' },
  { codigo: '52250', nombre: 'El Charco', departamentoCodigo: '52' },
  { codigo: '52254', nombre: 'El Penol', departamentoCodigo: '52' },
  { codigo: '52256', nombre: 'El Rosario', departamentoCodigo: '52' },
  { codigo: '52258', nombre: 'El Tablon de Gomez', departamentoCodigo: '52' },
  { codigo: '52260', nombre: 'El Tambo - Narino', departamentoCodigo: '52' },
  { codigo: '52287', nombre: 'Funes', departamentoCodigo: '52' },
  { codigo: '52317', nombre: 'Guachucal', departamentoCodigo: '52' },
  { codigo: '52320', nombre: 'Guaitarilla', departamentoCodigo: '52' },
  { codigo: '52323', nombre: 'Gualmatan', departamentoCodigo: '52' },
  { codigo: '52352', nombre: 'Iles', departamentoCodigo: '52' },
  { codigo: '52354', nombre: 'Imues', departamentoCodigo: '52' },
  { codigo: '52356', nombre: 'Ipiales', departamentoCodigo: '52' },
  { codigo: '52378', nombre: 'La Cruz', departamentoCodigo: '52' },
  { codigo: '52381', nombre: 'La Florida', departamentoCodigo: '52' },
  { codigo: '52385', nombre: 'La Llanada', departamentoCodigo: '52' },
  { codigo: '52390', nombre: 'La Tola', departamentoCodigo: '52' },
  { codigo: '52399', nombre: 'La Union - Narino', departamentoCodigo: '52' },
  { codigo: '52405', nombre: 'Leiva', departamentoCodigo: '52' },
  { codigo: '52411', nombre: 'Linares', departamentoCodigo: '52' },
  { codigo: '52418', nombre: 'Los Andes', departamentoCodigo: '52' },
  { codigo: '52427', nombre: 'Magui', departamentoCodigo: '52' },
  { codigo: '52435', nombre: 'Mallama', departamentoCodigo: '52' },
  { codigo: '52473', nombre: 'Mosquera - Narino', departamentoCodigo: '52' },
  { codigo: '52480', nombre: 'Narino - Narino', departamentoCodigo: '52' },
  { codigo: '52490', nombre: 'Olaya Herrera', departamentoCodigo: '52' },
  { codigo: '52506', nombre: 'Ospina', departamentoCodigo: '52' },
  { codigo: '52520', nombre: 'Francisco Pizarro', departamentoCodigo: '52' },
  { codigo: '52540', nombre: 'Policarpa', departamentoCodigo: '52' },
  { codigo: '52560', nombre: 'Potosi', departamentoCodigo: '52' },
  { codigo: '52565', nombre: 'Providencia - Narino', departamentoCodigo: '52' },
  { codigo: '52573', nombre: 'Puerres', departamentoCodigo: '52' },
  { codigo: '52585', nombre: 'Pupiales', departamentoCodigo: '52' },
  { codigo: '52612', nombre: 'Ricaurte - Narino', departamentoCodigo: '52' },
  { codigo: '52621', nombre: 'Roberto Payan', departamentoCodigo: '52' },
  { codigo: '52678', nombre: 'Samaniego', departamentoCodigo: '52' },
  { codigo: '52683', nombre: 'Sandona', departamentoCodigo: '52' },
  {
    codigo: '52685',
    nombre: 'San Bernardo - Narino',
    departamentoCodigo: '52',
  },
  { codigo: '52687', nombre: 'San Lorenzo', departamentoCodigo: '52' },
  { codigo: '52693', nombre: 'San Pablo - Narino', departamentoCodigo: '52' },
  { codigo: '52694', nombre: 'San Pedro de Cartago', departamentoCodigo: '52' },
  {
    codigo: '52696',
    nombre: 'Santa Barbara - Narino',
    departamentoCodigo: '52',
  },
  { codigo: '52699', nombre: 'Santacruz', departamentoCodigo: '52' },
  { codigo: '52720', nombre: 'Sapuyes', departamentoCodigo: '52' },
  { codigo: '52786', nombre: 'Taminango', departamentoCodigo: '52' },
  { codigo: '52788', nombre: 'Tangua', departamentoCodigo: '52' },
  { codigo: '52835', nombre: 'San Andres de Tumaco', departamentoCodigo: '52' },
  { codigo: '52838', nombre: 'Tuquerres', departamentoCodigo: '52' },
  { codigo: '52885', nombre: 'Yacuanquer', departamentoCodigo: '52' },
  { codigo: '54001', nombre: 'Cucuta', departamentoCodigo: '54' },
  { codigo: '54003', nombre: 'Abrego', departamentoCodigo: '54' },
  { codigo: '54051', nombre: 'Arboledas', departamentoCodigo: '54' },
  { codigo: '54099', nombre: 'Bochalema', departamentoCodigo: '54' },
  { codigo: '54109', nombre: 'Bucarasica', departamentoCodigo: '54' },
  { codigo: '54125', nombre: 'Cacota', departamentoCodigo: '54' },
  { codigo: '54128', nombre: 'Cachira', departamentoCodigo: '54' },
  { codigo: '54172', nombre: 'Chinacota', departamentoCodigo: '54' },
  { codigo: '54174', nombre: 'Chitaga', departamentoCodigo: '54' },
  { codigo: '54206', nombre: 'Convencion', departamentoCodigo: '54' },
  { codigo: '54223', nombre: 'Cucutilla', departamentoCodigo: '54' },
  { codigo: '54239', nombre: 'Durania', departamentoCodigo: '54' },
  { codigo: '54245', nombre: 'El Carmen', departamentoCodigo: '54' },
  { codigo: '54250', nombre: 'El Tarra', departamentoCodigo: '54' },
  { codigo: '54261', nombre: 'El Zulia', departamentoCodigo: '54' },
  { codigo: '54313', nombre: 'Gramalote', departamentoCodigo: '54' },
  { codigo: '54344', nombre: 'Hacari', departamentoCodigo: '54' },
  { codigo: '54347', nombre: 'Herran', departamentoCodigo: '54' },
  { codigo: '54377', nombre: 'Labateca', departamentoCodigo: '54' },
  { codigo: '54385', nombre: 'La Esperanza', departamentoCodigo: '54' },
  { codigo: '54398', nombre: 'La Playa', departamentoCodigo: '54' },
  { codigo: '54405', nombre: 'Los Patios', departamentoCodigo: '54' },
  { codigo: '54418', nombre: 'Lourdes', departamentoCodigo: '54' },
  { codigo: '54480', nombre: 'Mutiscua', departamentoCodigo: '54' },
  { codigo: '54498', nombre: 'Ocana', departamentoCodigo: '54' },
  { codigo: '54518', nombre: 'Pamplona', departamentoCodigo: '54' },
  { codigo: '54520', nombre: 'Pamplonita', departamentoCodigo: '54' },
  {
    codigo: '54553',
    nombre: 'Puerto Santander - Norte de Santander',
    departamentoCodigo: '54',
  },
  { codigo: '54599', nombre: 'Ragonvalia', departamentoCodigo: '54' },
  { codigo: '54660', nombre: 'Salazar', departamentoCodigo: '54' },
  { codigo: '54670', nombre: 'San Calixto', departamentoCodigo: '54' },
  {
    codigo: '54673',
    nombre: 'San Cayetano - Norte de Santander',
    departamentoCodigo: '54',
  },
  {
    codigo: '54680',
    nombre: 'Santiago - Norte de Santander',
    departamentoCodigo: '54',
  },
  { codigo: '54720', nombre: 'Sardinata', departamentoCodigo: '54' },
  { codigo: '54743', nombre: 'Silos', departamentoCodigo: '54' },
  { codigo: '54800', nombre: 'Teorama', departamentoCodigo: '54' },
  { codigo: '54810', nombre: 'Tibu', departamentoCodigo: '54' },
  {
    codigo: '54820',
    nombre: 'Toledo - Norte de Santander',
    departamentoCodigo: '54',
  },
  { codigo: '54871', nombre: 'Villa Caro', departamentoCodigo: '54' },
  { codigo: '54874', nombre: 'Villa del Rosario', departamentoCodigo: '54' },
  { codigo: '63001', nombre: 'Armenia - Quindio', departamentoCodigo: '63' },
  { codigo: '63111', nombre: 'Buenavista - Quindio', departamentoCodigo: '63' },
  { codigo: '63130', nombre: 'Calarca', departamentoCodigo: '63' },
  { codigo: '63190', nombre: 'Circasia', departamentoCodigo: '63' },
  { codigo: '63212', nombre: 'Cordoba - Quindio', departamentoCodigo: '63' },
  { codigo: '63272', nombre: 'Filandia', departamentoCodigo: '63' },
  { codigo: '63302', nombre: 'Genova', departamentoCodigo: '63' },
  { codigo: '63401', nombre: 'La Tebaida', departamentoCodigo: '63' },
  { codigo: '63470', nombre: 'Montenegro', departamentoCodigo: '63' },
  { codigo: '63548', nombre: 'Pijao', departamentoCodigo: '63' },
  { codigo: '63594', nombre: 'Quimbaya', departamentoCodigo: '63' },
  { codigo: '63690', nombre: 'Salento', departamentoCodigo: '63' },
  { codigo: '66001', nombre: 'Pereira', departamentoCodigo: '66' },
  { codigo: '66045', nombre: 'Apia', departamentoCodigo: '66' },
  { codigo: '66075', nombre: 'Balboa - Risaralda', departamentoCodigo: '66' },
  { codigo: '66088', nombre: 'Belen de Umbria', departamentoCodigo: '66' },
  { codigo: '66170', nombre: 'Dosquebradas', departamentoCodigo: '66' },
  { codigo: '66318', nombre: 'Guatica', departamentoCodigo: '66' },
  { codigo: '66383', nombre: 'La Celia', departamentoCodigo: '66' },
  { codigo: '66400', nombre: 'La Virginia', departamentoCodigo: '66' },
  { codigo: '66440', nombre: 'Marsella', departamentoCodigo: '66' },
  { codigo: '66456', nombre: 'Mistrato', departamentoCodigo: '66' },
  { codigo: '66572', nombre: 'Pueblo Rico', departamentoCodigo: '66' },
  { codigo: '66594', nombre: 'Quinchia', departamentoCodigo: '66' },
  { codigo: '66682', nombre: 'Santa Rosa de Cabal', departamentoCodigo: '66' },
  { codigo: '66687', nombre: 'Santuario', departamentoCodigo: '66' },
  { codigo: '68001', nombre: 'Bucaramanga', departamentoCodigo: '68' },
  { codigo: '68013', nombre: 'Aguada', departamentoCodigo: '68' },
  { codigo: '68020', nombre: 'Albania - Santander', departamentoCodigo: '68' },
  { codigo: '68051', nombre: 'Aratoca', departamentoCodigo: '68' },
  { codigo: '68077', nombre: 'Barbosa', departamentoCodigo: '68' },
  { codigo: '68079', nombre: 'Barichara', departamentoCodigo: '68' },
  { codigo: '68081', nombre: 'Barrancabermeja', departamentoCodigo: '68' },
  { codigo: '68092', nombre: 'Betulia - Santander', departamentoCodigo: '68' },
  { codigo: '68101', nombre: 'Bolivar - Santander', departamentoCodigo: '68' },
  { codigo: '68121', nombre: 'Cabrera - Santander', departamentoCodigo: '68' },
  { codigo: '68132', nombre: 'California', departamentoCodigo: '68' },
  { codigo: '68147', nombre: 'Capitanejo', departamentoCodigo: '68' },
  { codigo: '68152', nombre: 'Carcasi', departamentoCodigo: '68' },
  { codigo: '68160', nombre: 'Cepita', departamentoCodigo: '68' },
  { codigo: '68162', nombre: 'Cerrito', departamentoCodigo: '68' },
  { codigo: '68167', nombre: 'Charala', departamentoCodigo: '68' },
  { codigo: '68169', nombre: 'Charta', departamentoCodigo: '68' },
  { codigo: '68176', nombre: 'Chima', departamentoCodigo: '68' },
  { codigo: '68179', nombre: 'Chipata', departamentoCodigo: '68' },
  { codigo: '68190', nombre: 'Cimitarra', departamentoCodigo: '68' },
  {
    codigo: '68207',
    nombre: 'Concepcion - Santander',
    departamentoCodigo: '68',
  },
  { codigo: '68209', nombre: 'Confines', departamentoCodigo: '68' },
  { codigo: '68211', nombre: 'Contratacion', departamentoCodigo: '68' },
  { codigo: '68217', nombre: 'Coromoro', departamentoCodigo: '68' },
  { codigo: '68229', nombre: 'Curiti', departamentoCodigo: '68' },
  { codigo: '68235', nombre: 'El Carmen de Chucuri', departamentoCodigo: '68' },
  { codigo: '68245', nombre: 'El Guacamayo', departamentoCodigo: '68' },
  { codigo: '68250', nombre: 'El Penon - Santander', departamentoCodigo: '68' },
  { codigo: '68255', nombre: 'El Playon', departamentoCodigo: '68' },
  { codigo: '68264', nombre: 'Encino', departamentoCodigo: '68' },
  { codigo: '68266', nombre: 'Enciso', departamentoCodigo: '68' },
  { codigo: '68271', nombre: 'Florian', departamentoCodigo: '68' },
  { codigo: '68276', nombre: 'Floridablanca', departamentoCodigo: '68' },
  { codigo: '68296', nombre: 'Galan', departamentoCodigo: '68' },
  { codigo: '68298', nombre: 'Gambita', departamentoCodigo: '68' },
  { codigo: '68307', nombre: 'Giron', departamentoCodigo: '68' },
  { codigo: '68318', nombre: 'Guaca', departamentoCodigo: '68' },
  {
    codigo: '68320',
    nombre: 'Guadalupe - Santander',
    departamentoCodigo: '68',
  },
  { codigo: '68322', nombre: 'Guapota', departamentoCodigo: '68' },
  { codigo: '68324', nombre: 'Guavata', departamentoCodigo: '68' },
  { codigo: '68327', nombre: 'Guepsa', departamentoCodigo: '68' },
  { codigo: '68344', nombre: 'Hato', departamentoCodigo: '68' },
  { codigo: '68368', nombre: 'Jesus Maria', departamentoCodigo: '68' },
  { codigo: '68370', nombre: 'Jordan', departamentoCodigo: '68' },
  { codigo: '68377', nombre: 'La Belleza', departamentoCodigo: '68' },
  { codigo: '68385', nombre: 'Landazuri', departamentoCodigo: '68' },
  { codigo: '68397', nombre: 'La Paz - Santander', departamentoCodigo: '68' },
  { codigo: '68406', nombre: 'Lebrija', departamentoCodigo: '68' },
  { codigo: '68418', nombre: 'Los Santos', departamentoCodigo: '68' },
  { codigo: '68425', nombre: 'Macaravita', departamentoCodigo: '68' },
  { codigo: '68432', nombre: 'Malaga', departamentoCodigo: '68' },
  { codigo: '68444', nombre: 'Matanza', departamentoCodigo: '68' },
  { codigo: '68464', nombre: 'Mogotes', departamentoCodigo: '68' },
  { codigo: '68468', nombre: 'Molagavita', departamentoCodigo: '68' },
  { codigo: '68498', nombre: 'Ocamonte', departamentoCodigo: '68' },
  { codigo: '68500', nombre: 'Oiba', departamentoCodigo: '68' },
  { codigo: '68502', nombre: 'Onzaga', departamentoCodigo: '68' },
  { codigo: '68522', nombre: 'Palmar', departamentoCodigo: '68' },
  { codigo: '68524', nombre: 'Palmas del Socorro', departamentoCodigo: '68' },
  { codigo: '68533', nombre: 'Paramo', departamentoCodigo: '68' },
  { codigo: '68547', nombre: 'Piedecuesta', departamentoCodigo: '68' },
  { codigo: '68549', nombre: 'Pinchote', departamentoCodigo: '68' },
  { codigo: '68572', nombre: 'Puente Nacional', departamentoCodigo: '68' },
  { codigo: '68573', nombre: 'Puerto Parra', departamentoCodigo: '68' },
  { codigo: '68575', nombre: 'Puerto Wilches', departamentoCodigo: '68' },
  { codigo: '68615', nombre: 'Rionegro - Santander', departamentoCodigo: '68' },
  { codigo: '68655', nombre: 'Sabana de Torres', departamentoCodigo: '68' },
  {
    codigo: '68669',
    nombre: 'San Andres -  Santander',
    departamentoCodigo: '68',
  },
  { codigo: '68673', nombre: 'San Benito', departamentoCodigo: '68' },
  { codigo: '68679', nombre: 'San Gil', departamentoCodigo: '68' },
  { codigo: '68682', nombre: 'San Joaquin', departamentoCodigo: '68' },
  { codigo: '68684', nombre: 'San Jose de Miranda', departamentoCodigo: '68' },
  {
    codigo: '68686',
    nombre: 'San Miguel - Santander',
    departamentoCodigo: '68',
  },
  {
    codigo: '68689',
    nombre: 'San Vicente de Chucuri',
    departamentoCodigo: '68',
  },
  {
    codigo: '68705',
    nombre: 'Santa Barbara - Santander',
    departamentoCodigo: '68',
  },
  {
    codigo: '68720',
    nombre: 'Santa Helena del Opon',
    departamentoCodigo: '68',
  },
  { codigo: '68745', nombre: 'Simacota', departamentoCodigo: '68' },
  { codigo: '68755', nombre: 'Socorro', departamentoCodigo: '68' },
  { codigo: '68770', nombre: 'Suaita', departamentoCodigo: '68' },
  { codigo: '68773', nombre: 'Sucre - Santander', departamentoCodigo: '68' },
  { codigo: '68780', nombre: 'Surata', departamentoCodigo: '68' },
  { codigo: '68820', nombre: 'Tona', departamentoCodigo: '68' },
  { codigo: '68855', nombre: 'Valle de San Jose', departamentoCodigo: '68' },
  { codigo: '68861', nombre: 'Velez', departamentoCodigo: '68' },
  { codigo: '68867', nombre: 'Vetas', departamentoCodigo: '68' },
  {
    codigo: '68872',
    nombre: 'Villanueva - Santander',
    departamentoCodigo: '68',
  },
  { codigo: '68895', nombre: 'Zapatoca', departamentoCodigo: '68' },
  { codigo: '70001', nombre: 'Sincelejo', departamentoCodigo: '70' },
  { codigo: '70110', nombre: 'Buenavista - Sucre', departamentoCodigo: '70' },
  { codigo: '70124', nombre: 'Caimito', departamentoCodigo: '70' },
  { codigo: '70204', nombre: 'Coloso', departamentoCodigo: '70' },
  { codigo: '70215', nombre: 'Corozal', departamentoCodigo: '70' },
  { codigo: '70221', nombre: 'Covenas', departamentoCodigo: '70' },
  { codigo: '70230', nombre: 'Chalan', departamentoCodigo: '70' },
  { codigo: '70233', nombre: 'El Roble', departamentoCodigo: '70' },
  { codigo: '70235', nombre: 'Galeras', departamentoCodigo: '70' },
  { codigo: '70265', nombre: 'Guaranda', departamentoCodigo: '70' },
  { codigo: '70400', nombre: 'La Union - Sucre', departamentoCodigo: '70' },
  { codigo: '70418', nombre: 'Los Palmitos', departamentoCodigo: '70' },
  { codigo: '70429', nombre: 'Majagual', departamentoCodigo: '70' },
  { codigo: '70473', nombre: 'Morroa', departamentoCodigo: '70' },
  { codigo: '70508', nombre: 'Ovejas', departamentoCodigo: '70' },
  { codigo: '70523', nombre: 'Palmito', departamentoCodigo: '70' },
  { codigo: '70670', nombre: 'Sampues', departamentoCodigo: '70' },
  { codigo: '70678', nombre: 'San Benito Abad', departamentoCodigo: '70' },
  { codigo: '70702', nombre: 'San Juan de Betulia', departamentoCodigo: '70' },
  { codigo: '70708', nombre: 'San Marcos', departamentoCodigo: '70' },
  { codigo: '70713', nombre: 'San Onofre', departamentoCodigo: '70' },
  { codigo: '70717', nombre: 'San Pedro - Sucre', departamentoCodigo: '70' },
  { codigo: '70742', nombre: 'San Luis de Since', departamentoCodigo: '70' },
  { codigo: '70771', nombre: 'Sucre - Sucre', departamentoCodigo: '70' },
  { codigo: '70820', nombre: 'Santiago de Tolu', departamentoCodigo: '70' },
  { codigo: '70823', nombre: 'Tolu Viejo', departamentoCodigo: '70' },
  { codigo: '73001', nombre: 'Ibague', departamentoCodigo: '73' },
  { codigo: '73024', nombre: 'Alpujarra', departamentoCodigo: '73' },
  { codigo: '73026', nombre: 'Alvarado', departamentoCodigo: '73' },
  { codigo: '73030', nombre: 'Ambalema', departamentoCodigo: '73' },
  { codigo: '73043', nombre: 'Anzoategui', departamentoCodigo: '73' },
  { codigo: '73055', nombre: 'Armero', departamentoCodigo: '73' },
  { codigo: '73067', nombre: 'Ataco', departamentoCodigo: '73' },
  { codigo: '73124', nombre: 'Cajamarca', departamentoCodigo: '73' },
  { codigo: '73148', nombre: 'Carmen de Apicala', departamentoCodigo: '73' },
  { codigo: '73152', nombre: 'Casabianca', departamentoCodigo: '73' },
  { codigo: '73168', nombre: 'Chaparral', departamentoCodigo: '73' },
  { codigo: '73200', nombre: 'Coello', departamentoCodigo: '73' },
  { codigo: '73217', nombre: 'Coyaima', departamentoCodigo: '73' },
  { codigo: '73226', nombre: 'Cunday', departamentoCodigo: '73' },
  { codigo: '73236', nombre: 'Dolores', departamentoCodigo: '73' },
  { codigo: '73268', nombre: 'Espinal', departamentoCodigo: '73' },
  { codigo: '73270', nombre: 'Falan', departamentoCodigo: '73' },
  { codigo: '73275', nombre: 'Flandes', departamentoCodigo: '73' },
  { codigo: '73283', nombre: 'Fresno', departamentoCodigo: '73' },
  { codigo: '73319', nombre: 'Guamo', departamentoCodigo: '73' },
  { codigo: '73347', nombre: 'Herveo', departamentoCodigo: '73' },
  { codigo: '73349', nombre: 'Honda', departamentoCodigo: '73' },
  { codigo: '73352', nombre: 'Icononzo', departamentoCodigo: '73' },
  { codigo: '73408', nombre: 'Lerida', departamentoCodigo: '73' },
  { codigo: '73411', nombre: 'Libano', departamentoCodigo: '73' },
  { codigo: '73443', nombre: 'Mariquita', departamentoCodigo: '73' },
  { codigo: '73449', nombre: 'Melgar', departamentoCodigo: '73' },
  { codigo: '73461', nombre: 'Murillo', departamentoCodigo: '73' },
  { codigo: '73483', nombre: 'Natagaima', departamentoCodigo: '73' },
  { codigo: '73504', nombre: 'Ortega', departamentoCodigo: '73' },
  { codigo: '73520', nombre: 'Palocabildo', departamentoCodigo: '73' },
  { codigo: '73547', nombre: 'Piedras', departamentoCodigo: '73' },
  { codigo: '73555', nombre: 'Planadas', departamentoCodigo: '73' },
  { codigo: '73563', nombre: 'Prado', departamentoCodigo: '73' },
  { codigo: '73585', nombre: 'Purificacion', departamentoCodigo: '73' },
  { codigo: '73616', nombre: 'Rioblanco', departamentoCodigo: '73' },
  { codigo: '73622', nombre: 'Roncesvalles', departamentoCodigo: '73' },
  { codigo: '73624', nombre: 'Rovira', departamentoCodigo: '73' },
  { codigo: '73671', nombre: 'Saldana', departamentoCodigo: '73' },
  { codigo: '73675', nombre: 'San Antonio', departamentoCodigo: '73' },
  { codigo: '73678', nombre: 'San Luis - Tolima', departamentoCodigo: '73' },
  { codigo: '73686', nombre: 'Santa Isabel', departamentoCodigo: '73' },
  { codigo: '73770', nombre: 'Suarez - Tolima', departamentoCodigo: '73' },
  { codigo: '73854', nombre: 'Valle de San Juan', departamentoCodigo: '73' },
  { codigo: '73861', nombre: 'Venadillo', departamentoCodigo: '73' },
  { codigo: '73870', nombre: 'Villahermosa', departamentoCodigo: '73' },
  { codigo: '73873', nombre: 'Villarrica', departamentoCodigo: '73' },
  { codigo: '76001', nombre: 'Cali', departamentoCodigo: '76' },
  { codigo: '76020', nombre: 'Alcala', departamentoCodigo: '76' },
  { codigo: '76036', nombre: 'Andalucia', departamentoCodigo: '76' },
  { codigo: '76041', nombre: 'Ansermanuevo', departamentoCodigo: '76' },
  {
    codigo: '76054',
    nombre: 'Argelia - Valle del Cauca',
    departamentoCodigo: '76',
  },
  {
    codigo: '76100',
    nombre: 'Bolivar - Valle del Cauca',
    departamentoCodigo: '76',
  },
  { codigo: '76109', nombre: 'Buenaventura', departamentoCodigo: '76' },
  { codigo: '76111', nombre: 'Guadalajara de Buga', departamentoCodigo: '76' },
  { codigo: '76113', nombre: 'Bugalagrande', departamentoCodigo: '76' },
  { codigo: '76122', nombre: 'Caicedonia', departamentoCodigo: '76' },
  { codigo: '76126', nombre: 'Calima', departamentoCodigo: '76' },
  {
    codigo: '76130',
    nombre: 'Candelaria - Valle del Cauca',
    departamentoCodigo: '76',
  },
  { codigo: '76147', nombre: 'Cartago', departamentoCodigo: '76' },
  { codigo: '76233', nombre: 'Dagua', departamentoCodigo: '76' },
  { codigo: '76243', nombre: 'El Aguila', departamentoCodigo: '76' },
  { codigo: '76246', nombre: 'El Cairo', departamentoCodigo: '76' },
  { codigo: '76248', nombre: 'El Cerrito', departamentoCodigo: '76' },
  { codigo: '76250', nombre: 'El Dovio', departamentoCodigo: '76' },
  { codigo: '76275', nombre: 'Florida', departamentoCodigo: '76' },
  { codigo: '76306', nombre: 'Ginebra', departamentoCodigo: '76' },
  { codigo: '76318', nombre: 'Guacari', departamentoCodigo: '76' },
  { codigo: '76364', nombre: 'Jamundi', departamentoCodigo: '76' },
  { codigo: '76377', nombre: 'La Cumbre', departamentoCodigo: '76' },
  {
    codigo: '76400',
    nombre: 'La Union - Valle del Cauca',
    departamentoCodigo: '76',
  },
  {
    codigo: '76403',
    nombre: 'La Victoria - Valle del Cauca',
    departamentoCodigo: '76',
  },
  { codigo: '76497', nombre: 'Obando', departamentoCodigo: '76' },
  { codigo: '76520', nombre: 'Palmira', departamentoCodigo: '76' },
  { codigo: '76563', nombre: 'Pradera', departamentoCodigo: '76' },
  {
    codigo: '76606',
    nombre: 'Restrepo - Valle del Cauca',
    departamentoCodigo: '76',
  },
  { codigo: '76616', nombre: 'Riofrio', departamentoCodigo: '76' },
  { codigo: '76622', nombre: 'Roldanillo', departamentoCodigo: '76' },
  {
    codigo: '76670',
    nombre: 'San Pedro - Valle del Cauca',
    departamentoCodigo: '76',
  },
  { codigo: '76736', nombre: 'Sevilla', departamentoCodigo: '76' },
  { codigo: '76823', nombre: 'Toro', departamentoCodigo: '76' },
  { codigo: '76828', nombre: 'Trujillo', departamentoCodigo: '76' },
  { codigo: '76834', nombre: 'Tulua', departamentoCodigo: '76' },
  { codigo: '76845', nombre: 'Ulloa', departamentoCodigo: '76' },
  { codigo: '76863', nombre: 'Versalles', departamentoCodigo: '76' },
  { codigo: '76869', nombre: 'Vijes', departamentoCodigo: '76' },
  { codigo: '76890', nombre: 'Yotoco', departamentoCodigo: '76' },
  { codigo: '76892', nombre: 'Yumbo', departamentoCodigo: '76' },
  { codigo: '76895', nombre: 'Zarzal', departamentoCodigo: '76' },
  { codigo: '81001', nombre: 'Arauca', departamentoCodigo: '81' },
  { codigo: '81065', nombre: 'Arauquita', departamentoCodigo: '81' },
  { codigo: '81220', nombre: 'Cravo Norte', departamentoCodigo: '81' },
  { codigo: '81300', nombre: 'Fortul', departamentoCodigo: '81' },
  { codigo: '81591', nombre: 'Puerto Rondon', departamentoCodigo: '81' },
  { codigo: '81736', nombre: 'Saravena', departamentoCodigo: '81' },
  { codigo: '81794', nombre: 'Tame', departamentoCodigo: '81' },
  { codigo: '85001', nombre: 'Yopal', departamentoCodigo: '85' },
  { codigo: '85010', nombre: 'Aguazul', departamentoCodigo: '85' },
  { codigo: '85015', nombre: 'Chameza', departamentoCodigo: '85' },
  { codigo: '85125', nombre: 'Hato Corozal', departamentoCodigo: '85' },
  { codigo: '85136', nombre: 'La Salina', departamentoCodigo: '85' },
  { codigo: '85139', nombre: 'Mani', departamentoCodigo: '85' },
  { codigo: '85162', nombre: 'Monterrey', departamentoCodigo: '85' },
  { codigo: '85225', nombre: 'Nunchia', departamentoCodigo: '85' },
  { codigo: '85230', nombre: 'Orocue', departamentoCodigo: '85' },
  { codigo: '85250', nombre: 'Paz de Ariporo', departamentoCodigo: '85' },
  { codigo: '85263', nombre: 'Pore', departamentoCodigo: '85' },
  { codigo: '85279', nombre: 'Recetor', departamentoCodigo: '85' },
  {
    codigo: '85300',
    nombre: 'Sabanalarga - Casanare',
    departamentoCodigo: '85',
  },
  { codigo: '85315', nombre: 'Sacama', departamentoCodigo: '85' },
  { codigo: '85325', nombre: 'San Luis de Palenque', departamentoCodigo: '85' },
  { codigo: '85400', nombre: 'Tamara', departamentoCodigo: '85' },
  { codigo: '85410', nombre: 'Tauramena', departamentoCodigo: '85' },
  { codigo: '85430', nombre: 'Trinidad', departamentoCodigo: '85' },
  {
    codigo: '85440',
    nombre: 'Villanueva - Casanare',
    departamentoCodigo: '85',
  },
  { codigo: '86001', nombre: 'Mocoa', departamentoCodigo: '86' },
  { codigo: '86219', nombre: 'Colon - Putumayo', departamentoCodigo: '86' },
  { codigo: '86320', nombre: 'Orito', departamentoCodigo: '86' },
  { codigo: '86568', nombre: 'Puerto Asis', departamentoCodigo: '86' },
  { codigo: '86569', nombre: 'Puerto Caicedo', departamentoCodigo: '86' },
  { codigo: '86571', nombre: 'Puerto Guzman', departamentoCodigo: '86' },
  { codigo: '86573', nombre: 'Leguizamo', departamentoCodigo: '86' },
  { codigo: '86749', nombre: 'Sibundoy', departamentoCodigo: '86' },
  {
    codigo: '86755',
    nombre: 'San Francisco -  Putumayo',
    departamentoCodigo: '86',
  },
  {
    codigo: '86757',
    nombre: 'San Miguel - Putumayo',
    departamentoCodigo: '86',
  },
  { codigo: '86760', nombre: 'Santiago - Putumayo', departamentoCodigo: '86' },
  { codigo: '86865', nombre: 'Valle del Guamuez', departamentoCodigo: '86' },
  { codigo: '86885', nombre: 'Villagarzon', departamentoCodigo: '86' },
  {
    codigo: '88001',
    nombre: 'San Andres -  Arch. de San Andres',
    departamentoCodigo: '88',
  },
  {
    codigo: '88564',
    nombre: 'Providencia - Arch. de San Andres',
    departamentoCodigo: '88',
  },
  { codigo: '91001', nombre: 'Leticia', departamentoCodigo: '91' },
  { codigo: '91263', nombre: 'El Encanto', departamentoCodigo: '91' },
  { codigo: '91405', nombre: 'La Chorrera', departamentoCodigo: '91' },
  { codigo: '91407', nombre: 'La Pedrera', departamentoCodigo: '91' },
  {
    codigo: '91430',
    nombre: 'La Victoria - Amazonas',
    departamentoCodigo: '91',
  },
  { codigo: '91460', nombre: 'Miriti - Parana', departamentoCodigo: '91' },
  { codigo: '91530', nombre: 'Puerto Alegria', departamentoCodigo: '91' },
  { codigo: '91536', nombre: 'Puerto Arica', departamentoCodigo: '91' },
  { codigo: '91540', nombre: 'Puerto Narino', departamentoCodigo: '91' },
  {
    codigo: '91669',
    nombre: 'Puerto Santander - Amazonas',
    departamentoCodigo: '91',
  },
  { codigo: '91798', nombre: 'Tarapaca', departamentoCodigo: '91' },
  { codigo: '94001', nombre: 'Inirida', departamentoCodigo: '94' },
  { codigo: '94343', nombre: 'Barranco Minas', departamentoCodigo: '94' },
  { codigo: '94663', nombre: 'Mapiripana', departamentoCodigo: '94' },
  { codigo: '94883', nombre: 'San Felipe', departamentoCodigo: '94' },
  { codigo: '94884', nombre: 'Puerto Colombia', departamentoCodigo: '94' },
  { codigo: '94885', nombre: 'La Guadalupe', departamentoCodigo: '94' },
  { codigo: '94886', nombre: 'Cacahual', departamentoCodigo: '94' },
  { codigo: '94887', nombre: 'Pana Pana', departamentoCodigo: '94' },
  { codigo: '94888', nombre: 'Morichal', departamentoCodigo: '94' },
  {
    // Corregido: el archivo fuente traía departamentoCodigo '94' (Guainía)
    // para esta fila — un typo, dado que el propio código '95001' y las
    // demás ciudades de Guaviare en el mismo archivo usan '95', y San José
    // del Guaviare es la capital de ese departamento, no de Guainía.
    codigo: '95001',
    nombre: 'San Jose del Guaviare',
    departamentoCodigo: '95',
  },
  { codigo: '95015', nombre: 'Calamar - Guaviare', departamentoCodigo: '95' },
  { codigo: '95025', nombre: 'El Retorno', departamentoCodigo: '95' },
  {
    codigo: '95200',
    nombre: 'Miraflores - Guaviare',
    departamentoCodigo: '95',
  },
  { codigo: '97001', nombre: 'Mitu', departamentoCodigo: '97' },
  { codigo: '97161', nombre: 'Caruru', departamentoCodigo: '97' },
  { codigo: '97511', nombre: 'Pacoa', departamentoCodigo: '97' },
  { codigo: '97666', nombre: 'Taraira', departamentoCodigo: '97' },
  { codigo: '97777', nombre: 'Papunaua', departamentoCodigo: '97' },
  { codigo: '97889', nombre: 'Yavarate', departamentoCodigo: '97' },
  { codigo: '99001', nombre: 'Puerto Carreno', departamentoCodigo: '99' },
  { codigo: '99524', nombre: 'La Primavera', departamentoCodigo: '99' },
  { codigo: '99624', nombre: 'Santa Rosalia', departamentoCodigo: '99' },
  { codigo: '99773', nombre: 'Cumaribo', departamentoCodigo: '99' },
];
